<?php

use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cities')->delete();
        DB::table('cities')->insert([
            ['id' => '2', 'title' => 'آذربایجان شرقی', 'parent_id' => '0'],
            ['id' => '3', 'title' => 'آذربایجان غربی', 'parent_id' => '0'],
            ['id' => '4', 'title' => 'اردبیل', 'parent_id' => '0'],
            ['id' => '5', 'title' => 'اصفهان', 'parent_id' => '0'],
            ['id' => '6', 'title' => 'البرز', 'parent_id' => '0'],
            ['id' => '7', 'title' => 'ایلام', 'parent_id' => '0'],
            ['id' => '8', 'title' => 'بوشهر', 'parent_id' => '0'],
            ['id' => '9', 'title' => 'تهران', 'parent_id' => '0'],
            ['id' => '10', 'title' => 'چهارمحال و بختیاری', 'parent_id' => '0'],
            ['id' => '11', 'title' => 'خراسان جنوبی', 'parent_id' => '0'],
            ['id' => '12', 'title' => 'خراسان رضوی', 'parent_id' => '0'],
            ['id' => '13', 'title' => 'خراسان شمالی', 'parent_id' => '0'],
            ['id' => '14', 'title' => 'خوزستان', 'parent_id' => '0'],
            ['id' => '15', 'title' => 'زنجان', 'parent_id' => '0'],
            ['id' => '16', 'title' => 'سمنان', 'parent_id' => '0'],
            ['id' => '17', 'title' => 'سیستان و بلوچستان', 'parent_id' => '0'],
            ['id' => '18', 'title' => 'فارس', 'parent_id' => '0'],
            ['id' => '19', 'title' => 'قزوین', 'parent_id' => '0'],
            ['id' => '20', 'title' => 'قم', 'parent_id' => '0'],
            ['id' => '21', 'title' => 'کردستان', 'parent_id' => '0'],
            ['id' => '22', 'title' => 'کرمان', 'parent_id' => '0'],
            ['id' => '23', 'title' => 'کرمانشاه', 'parent_id' => '0'],
            ['id' => '24', 'title' => 'کهگیلویه و بویراحمد', 'parent_id' => '0'],
            ['id' => '25', 'title' => 'گلستان', 'parent_id' => '0'],
            ['id' => '26', 'title' => 'گیلان', 'parent_id' => '0'],
            ['id' => '27', 'title' => 'لرستان', 'parent_id' => '0'],
            ['id' => '28', 'title' => 'مازندران', 'parent_id' => '0'],
            ['id' => '29', 'title' => 'مرکزی', 'parent_id' => '0'],
            ['id' => '30', 'title' => 'هرمزگان', 'parent_id' => '0'],
            ['id' => '31', 'title' => 'همدان', 'parent_id' => '0'],
            ['id' => '32', 'title' => 'یزد', 'parent_id' => '0'],


            ['id' => '33', 'title' => 'اهر', 'parent_id' => '2'],
            ['id' => '34', 'title' => 'هوراند', 'parent_id' => '2'],
            ['id' => '35', 'title' => 'باسمنج', 'parent_id' => '2'],
            ['id' => '36', 'title' => 'تبريز', 'parent_id' => '2'],
            ['id' => '37', 'title' => 'سردرود', 'parent_id' => '2'],
            ['id' => '38', 'title' => 'خسروشاه', 'parent_id' => '2'],
            ['id' => '39', 'title' => 'سراب', 'parent_id' => '2'],
            ['id' => '40', 'title' => 'مهربان', 'parent_id' => '2'],
            ['id' => '41', 'title' => 'شربيان', 'parent_id' => '2'],
            ['id' => '42', 'title' => 'دوزدوزان', 'parent_id' => '2'],
            ['id' => '43', 'title' => 'مراغه', 'parent_id' => '2'],
            ['id' => '44', 'title' => 'خداجو-خراجو', 'parent_id' => '2'],
            ['id' => '45', 'title' => 'زنوز', 'parent_id' => '2'],
            ['id' => '46', 'title' => 'مرند', 'parent_id' => '2'],
            ['id' => '47', 'title' => 'کشکسراي', 'parent_id' => '2'],
            ['id' => '48', 'title' => 'بناب مرند', 'parent_id' => '2'],
            ['id' => '49', 'title' => 'يامچي', 'parent_id' => '2'],
            ['id' => '50', 'title' => 'ترکمانچاي', 'parent_id' => '2'],
            ['id' => '51', 'title' => 'آقکند', 'parent_id' => '2'],
            ['id' => '52', 'title' => 'ترک', 'parent_id' => '2'],
            ['id' => '53', 'title' => 'ميانه', 'parent_id' => '2'],
            ['id' => '54', 'title' => 'اچاچي', 'parent_id' => '2'],
            ['id' => '55', 'title' => 'هشترود', 'parent_id' => '2'],
            ['id' => '56', 'title' => 'نظرکهريزي', 'parent_id' => '2'],
            ['id' => '57', 'title' => 'بناب', 'parent_id' => '2'],
            ['id' => '58', 'title' => 'تيکمه داش', 'parent_id' => '2'],
            ['id' => '59', 'title' => 'بستان آباد', 'parent_id' => '2'],
            ['id' => '60', 'title' => 'صوفيان', 'parent_id' => '2'],
            ['id' => '61', 'title' => 'خامنه', 'parent_id' => '2'],
            ['id' => '62', 'title' => 'شبستر', 'parent_id' => '2'],
            ['id' => '63', 'title' => 'شرفخانه', 'parent_id' => '2'],
            ['id' => '64', 'title' => 'شندآباد', 'parent_id' => '2'],
            ['id' => '65', 'title' => 'سيس', 'parent_id' => '2'],
            ['id' => '66', 'title' => 'وايقان', 'parent_id' => '2'],
            ['id' => '67', 'title' => 'کوزه کنان', 'parent_id' => '2'],
            ['id' => '68', 'title' => 'تسوج', 'parent_id' => '2'],
            ['id' => '69', 'title' => 'کليبر', 'parent_id' => '2'],
            ['id' => '70', 'title' => 'آبش احمد', 'parent_id' => '2'],
            ['id' => '71', 'title' => 'خواجه', 'parent_id' => '2'],
            ['id' => '72', 'title' => 'هريس', 'parent_id' => '2'],
            ['id' => '73', 'title' => 'زرنق', 'parent_id' => '2'],
            ['id' => '74', 'title' => 'بخشايش', 'parent_id' => '2'],
            ['id' => '75', 'title' => 'کلوانق', 'parent_id' => '2'],
            ['id' => '76', 'title' => 'سيه رود', 'parent_id' => '2'],
            ['id' => '77', 'title' => 'جلفا', 'parent_id' => '2'],
            ['id' => '78', 'title' => 'هاديشهر', 'parent_id' => '2'],
            ['id' => '79', 'title' => 'ليلان', 'parent_id' => '2'],
            ['id' => '80', 'title' => 'ملکان', 'parent_id' => '2'],
            ['id' => '81', 'title' => 'مبارک شهر', 'parent_id' => '2'],
            ['id' => '82', 'title' => 'گوگان', 'parent_id' => '2'],
            ['id' => '83', 'title' => 'تيمورلو', 'parent_id' => '2'],
            ['id' => '84', 'title' => 'ممقان', 'parent_id' => '2'],
            ['id' => '85', 'title' => 'آذرشهر', 'parent_id' => '2'],
            ['id' => '86', 'title' => 'ايلخچي', 'parent_id' => '2'],
            ['id' => '87', 'title' => 'اسکو', 'parent_id' => '2'],
            ['id' => '88', 'title' => 'سهند', 'parent_id' => '2'],
            ['id' => '89', 'title' => 'قره آغاج', 'parent_id' => '2'],
            ['id' => '90', 'title' => 'خاروانا', 'parent_id' => '2'],
            ['id' => '91', 'title' => 'ورزقان', 'parent_id' => '2'],
            ['id' => '92', 'title' => 'جوان قلعه', 'parent_id' => '2'],
            ['id' => '93', 'title' => 'عجب شير', 'parent_id' => '2'],
            ['id' => '94', 'title' => 'خمارلو', 'parent_id' => '2'],
            ['id' => '95', 'title' => 'قوشچي', 'parent_id' => '3'],
            ['id' => '96', 'title' => 'سيلوانه', 'parent_id' => '3'],
            ['id' => '97', 'title' => 'سرو', 'parent_id' => '3'],
            ['id' => '98', 'title' => 'اروميه', 'parent_id' => '3'],
            ['id' => '99', 'title' => 'نوشين', 'parent_id' => '3'],
            ['id' => '100', 'title' => 'پيرانشهر', 'parent_id' => '3'],
            ['id' => '101', 'title' => 'گردكشانه', 'parent_id' => '3'],
            ['id' => '102', 'title' => 'خوئ', 'parent_id' => '3'],
            ['id' => '103', 'title' => 'فيرورق', 'parent_id' => '3'],
            ['id' => '104', 'title' => 'ديزج ديز', 'parent_id' => '3'],
            ['id' => '105', 'title' => 'زرآباد', 'parent_id' => '3'],
            ['id' => '106', 'title' => 'ايواوغلي', 'parent_id' => '3'],
            ['id' => '107', 'title' => 'قطور', 'parent_id' => '3'],
            ['id' => '108', 'title' => 'سردشت', 'parent_id' => '3'],
            ['id' => '109', 'title' => 'ربط', 'parent_id' => '3'],
            ['id' => '110', 'title' => 'ميرآباد', 'parent_id' => '3'],
            ['id' => '111', 'title' => 'تازه شهر', 'parent_id' => '3'],
            ['id' => '112', 'title' => 'سلماس', 'parent_id' => '3'],
            ['id' => '113', 'title' => 'ماكو', 'parent_id' => '3'],
            ['id' => '114', 'title' => 'بازرگان', 'parent_id' => '3'],
            ['id' => '115', 'title' => 'خليفان', 'parent_id' => '3'],
            ['id' => '116', 'title' => 'مهاباد', 'parent_id' => '3'],
            ['id' => '117', 'title' => 'مياندوآب', 'parent_id' => '3'],
            ['id' => '118', 'title' => 'چهاربرج', 'parent_id' => '3'],
            ['id' => '119', 'title' => 'باروق', 'parent_id' => '3'],
            ['id' => '120', 'title' => 'نقده', 'parent_id' => '3'],
            ['id' => '121', 'title' => 'محمديار', 'parent_id' => '3'],
            ['id' => '122', 'title' => 'سيمينه', 'parent_id' => '3'],
            ['id' => '123', 'title' => 'بوكان', 'parent_id' => '3'],
            ['id' => '124', 'title' => 'شاهين دژ', 'parent_id' => '3'],
            ['id' => '125', 'title' => 'محمودآباد', 'parent_id' => '3'],
            ['id' => '126', 'title' => 'كشاورز', 'parent_id' => '3'],
            ['id' => '127', 'title' => 'تكاب', 'parent_id' => '3'],
            ['id' => '128', 'title' => 'اشنويه', 'parent_id' => '3'],
            ['id' => '129', 'title' => 'نالوس', 'parent_id' => '3'],
            ['id' => '130', 'title' => 'آواجيق', 'parent_id' => '3'],
            ['id' => '131', 'title' => 'سيه چشمه', 'parent_id' => '3'],
            ['id' => '132', 'title' => 'نازك عليا', 'parent_id' => '3'],
            ['id' => '133', 'title' => 'پلدشت', 'parent_id' => '3'],
            ['id' => '134', 'title' => 'قره ضياءالدين', 'parent_id' => '3'],
            ['id' => '135', 'title' => 'مرگنلر', 'parent_id' => '3'],
            ['id' => '136', 'title' => 'شوط', 'parent_id' => '3'],
            ['id' => '137', 'title' => 'اردبيل', 'parent_id' => '4'],
            ['id' => '138', 'title' => 'اسلام اباد', 'parent_id' => '4'],
            ['id' => '139', 'title' => 'اصلاندوز', 'parent_id' => '4'],
            ['id' => '140', 'title' => 'آبي بيگلو', 'parent_id' => '4'],
            ['id' => '141', 'title' => 'بيله سوار', 'parent_id' => '4'],
            ['id' => '142', 'title' => 'پارس آباد', 'parent_id' => '4'],
            ['id' => '143', 'title' => 'تازه كند', 'parent_id' => '4'],
            ['id' => '144', 'title' => 'تازه كندانگوت', 'parent_id' => '4'],
            ['id' => '145', 'title' => 'جعفرآباد', 'parent_id' => '4'],
            ['id' => '146', 'title' => 'خلخال', 'parent_id' => '4'],
            ['id' => '147', 'title' => 'رضي', 'parent_id' => '4'],
            ['id' => '148', 'title' => 'سرعين', 'parent_id' => '4'],
            ['id' => '149', 'title' => 'عنبران', 'parent_id' => '4'],
            ['id' => '150', 'title' => 'فخراباد', 'parent_id' => '4'],
            ['id' => '151', 'title' => 'قصابه', 'parent_id' => '4'],
            ['id' => '152', 'title' => 'كلور', 'parent_id' => '4'],
            ['id' => '153', 'title' => 'كوراييم', 'parent_id' => '4'],
            ['id' => '154', 'title' => 'گرمي', 'parent_id' => '4'],
            ['id' => '155', 'title' => 'گيوئ', 'parent_id' => '4'],
            ['id' => '156', 'title' => 'لاهرود', 'parent_id' => '4'],
            ['id' => '157', 'title' => 'مرادلو', 'parent_id' => '4'],
            ['id' => '158', 'title' => 'مشگين شهر', 'parent_id' => '4'],
            ['id' => '159', 'title' => 'نمين', 'parent_id' => '4'],
            ['id' => '160', 'title' => 'نير', 'parent_id' => '4'],
            ['id' => '161', 'title' => 'هشتجين', 'parent_id' => '4'],
            ['id' => '162', 'title' => 'هير', 'parent_id' => '4'],
            ['id' => '163', 'title' => 'ابريشم', 'parent_id' => '5'],
            ['id' => '164', 'title' => 'ابوزيدآباد', 'parent_id' => '5'],
            ['id' => '165', 'title' => 'اردستان', 'parent_id' => '5'],
            ['id' => '166', 'title' => 'اژيه', 'parent_id' => '5'],
            ['id' => '167', 'title' => 'اصغرآباد', 'parent_id' => '5'],
            ['id' => '168', 'title' => 'اصفهان', 'parent_id' => '5'],
            ['id' => '169', 'title' => 'افوس', 'parent_id' => '5'],
            ['id' => '170', 'title' => 'انارک', 'parent_id' => '5'],
            ['id' => '171', 'title' => 'ايمانشهر', 'parent_id' => '5'],
            ['id' => '172', 'title' => 'آران وبيدگل', 'parent_id' => '5'],
            ['id' => '173', 'title' => 'بادرود', 'parent_id' => '5'],
            ['id' => '174', 'title' => 'باغ بهادران', 'parent_id' => '5'],
            ['id' => '175', 'title' => 'باغشاد', 'parent_id' => '5'],
            ['id' => '176', 'title' => 'بافران', 'parent_id' => '5'],
            ['id' => '177', 'title' => 'برزک', 'parent_id' => '5'],
            ['id' => '178', 'title' => 'برف انبار', 'parent_id' => '5'],
            ['id' => '179', 'title' => 'بويين ومياندشت', 'parent_id' => '5'],
            ['id' => '180', 'title' => 'بهاران شهر', 'parent_id' => '5'],
            ['id' => '181', 'title' => 'بهارستان', 'parent_id' => '5'],
            ['id' => '182', 'title' => 'پيربکران', 'parent_id' => '5'],
            ['id' => '183', 'title' => 'تودشک', 'parent_id' => '5'],
            ['id' => '184', 'title' => 'تيران', 'parent_id' => '5'],
            ['id' => '185', 'title' => 'جندق', 'parent_id' => '5'],
            ['id' => '186', 'title' => 'جوزدان', 'parent_id' => '5'],
            ['id' => '187', 'title' => 'جوشقان قالي', 'parent_id' => '5'],
            ['id' => '188', 'title' => 'چادگان', 'parent_id' => '5'],
            ['id' => '189', 'title' => 'چرمهين', 'parent_id' => '5'],
            ['id' => '190', 'title' => 'چمگردان', 'parent_id' => '5'],
            ['id' => '191', 'title' => 'حبيب آباد', 'parent_id' => '5'],
            ['id' => '192', 'title' => 'حسن اباد', 'parent_id' => '5'],
            ['id' => '193', 'title' => 'حنا', 'parent_id' => '5'],
            ['id' => '194', 'title' => 'خالدآباد', 'parent_id' => '5'],
            ['id' => '195', 'title' => 'خميني شهر', 'parent_id' => '5'],
            ['id' => '196', 'title' => 'خوانسار', 'parent_id' => '5'],
            ['id' => '197', 'title' => 'خور', 'parent_id' => '5'],
            ['id' => '198', 'title' => 'خورزوق', 'parent_id' => '5'],
            ['id' => '199', 'title' => 'داران', 'parent_id' => '5'],
            ['id' => '200', 'title' => 'دامنه', 'parent_id' => '5'],
            ['id' => '201', 'title' => 'درچه', 'parent_id' => '5'],
            ['id' => '202', 'title' => 'دستگرد', 'parent_id' => '5'],
            ['id' => '203', 'title' => 'دولت آباد', 'parent_id' => '5'],
            ['id' => '204', 'title' => 'دهاقان', 'parent_id' => '5'],
            ['id' => '205', 'title' => 'دهق', 'parent_id' => '5'],
            ['id' => '206', 'title' => 'ديزيچه', 'parent_id' => '5'],
            ['id' => '207', 'title' => 'رزوه', 'parent_id' => '5'],
            ['id' => '208', 'title' => 'رضوانشهر', 'parent_id' => '5'],
            ['id' => '209', 'title' => 'زازران', 'parent_id' => '5'],
            ['id' => '210', 'title' => 'زاينده رود', 'parent_id' => '5'],
            ['id' => '211', 'title' => 'زرين شهر', 'parent_id' => '5'],
            ['id' => '212', 'title' => 'زواره', 'parent_id' => '5'],
            ['id' => '213', 'title' => 'زيار', 'parent_id' => '5'],
            ['id' => '214', 'title' => 'زيباشهر', 'parent_id' => '5'],
            ['id' => '215', 'title' => 'سده لنجان', 'parent_id' => '5'],
            ['id' => '216', 'title' => 'سفيدشهر', 'parent_id' => '5'],
            ['id' => '217', 'title' => 'سگزي', 'parent_id' => '5'],
            ['id' => '218', 'title' => 'سميرم', 'parent_id' => '5'],
            ['id' => '219', 'title' => 'سين', 'parent_id' => '5'],
            ['id' => '220', 'title' => 'شاپورآباد', 'parent_id' => '5'],
            ['id' => '221', 'title' => 'شاهين شهر', 'parent_id' => '5'],
            ['id' => '222', 'title' => 'شهرضا', 'parent_id' => '5'],
            ['id' => '223', 'title' => 'طالخونچه', 'parent_id' => '5'],
            ['id' => '224', 'title' => 'طرق رود', 'parent_id' => '5'],
            ['id' => '225', 'title' => 'عسگران', 'parent_id' => '5'],
            ['id' => '226', 'title' => 'علويجه', 'parent_id' => '5'],
            ['id' => '227', 'title' => 'فرخي', 'parent_id' => '5'],
            ['id' => '228', 'title' => 'فريدونشهر', 'parent_id' => '5'],
            ['id' => '229', 'title' => 'فلاورجان', 'parent_id' => '5'],
            ['id' => '230', 'title' => 'فولادشهر', 'parent_id' => '5'],
            ['id' => '231', 'title' => 'قمصر', 'parent_id' => '5'],
            ['id' => '232', 'title' => 'قهجاورستان', 'parent_id' => '5'],
            ['id' => '233', 'title' => 'قهدريجان', 'parent_id' => '5'],
            ['id' => '234', 'title' => 'کاشان', 'parent_id' => '5'],
            ['id' => '235', 'title' => 'کامو و چوگان', 'parent_id' => '5'],
            ['id' => '236', 'title' => 'کرکوند', 'parent_id' => '5'],
            ['id' => '237', 'title' => 'کليشادوسودرجان', 'parent_id' => '5'],
            ['id' => '238', 'title' => 'کمشجه', 'parent_id' => '5'],
            ['id' => '239', 'title' => 'کمه', 'parent_id' => '5'],
            ['id' => '240', 'title' => 'کوشک', 'parent_id' => '5'],
            ['id' => '241', 'title' => 'کوهپايه', 'parent_id' => '5'],
            ['id' => '242', 'title' => 'کهريزسنگ', 'parent_id' => '5'],
            ['id' => '243', 'title' => 'گرگاب', 'parent_id' => '5'],
            ['id' => '244', 'title' => 'گزبرخوار', 'parent_id' => '5'],
            ['id' => '245', 'title' => 'گلپايگان', 'parent_id' => '5'],
            ['id' => '246', 'title' => 'گلدشت', 'parent_id' => '5'],
            ['id' => '247', 'title' => 'گلشن', 'parent_id' => '5'],
            ['id' => '248', 'title' => 'گلشهر', 'parent_id' => '5'],
            ['id' => '249', 'title' => 'گوگد', 'parent_id' => '5'],
            ['id' => '250', 'title' => 'لاي بيد', 'parent_id' => '5'],
            ['id' => '251', 'title' => 'مبارکه', 'parent_id' => '5'],
            ['id' => '252', 'title' => 'مجلسي', 'parent_id' => '5'],
            ['id' => '253', 'title' => 'محمدآباد', 'parent_id' => '5'],
            ['id' => '254', 'title' => 'مشکات', 'parent_id' => '5'],
            ['id' => '255', 'title' => 'منظريه', 'parent_id' => '5'],
            ['id' => '256', 'title' => 'مهاباد', 'parent_id' => '5'],
            ['id' => '257', 'title' => 'ميمه', 'parent_id' => '5'],
            ['id' => '258', 'title' => 'نايين', 'parent_id' => '5'],
            ['id' => '259', 'title' => 'نجف آباد', 'parent_id' => '5'],
            ['id' => '260', 'title' => 'نصرآباد', 'parent_id' => '5'],
            ['id' => '261', 'title' => 'نطنز', 'parent_id' => '5'],
            ['id' => '262', 'title' => 'نوش آباد', 'parent_id' => '5'],
            ['id' => '263', 'title' => 'نياسر', 'parent_id' => '5'],
            ['id' => '264', 'title' => 'نيک آباد', 'parent_id' => '5'],
            ['id' => '265', 'title' => 'ورزنه', 'parent_id' => '5'],
            ['id' => '266', 'title' => 'ورنامخواست', 'parent_id' => '5'],
            ['id' => '267', 'title' => 'وزوان', 'parent_id' => '5'],
            ['id' => '268', 'title' => 'ونک', 'parent_id' => '5'],
            ['id' => '269', 'title' => 'هرند', 'parent_id' => '5'],
            ['id' => '270', 'title' => 'اشتهارد', 'parent_id' => '6'],
            ['id' => '271', 'title' => 'آسارا', 'parent_id' => '6'],
            ['id' => '272', 'title' => 'تنکمان', 'parent_id' => '6'],
            ['id' => '273', 'title' => 'چهارباغ', 'parent_id' => '6'],
            ['id' => '274', 'title' => 'شهرجديدهشتگرد', 'parent_id' => '6'],
            ['id' => '275', 'title' => 'طالقان', 'parent_id' => '6'],
            ['id' => '276', 'title' => 'فرديس', 'parent_id' => '6'],
            ['id' => '277', 'title' => 'کرج', 'parent_id' => '6'],
            ['id' => '278', 'title' => 'کمال شهر', 'parent_id' => '6'],
            ['id' => '279', 'title' => 'کوهسار', 'parent_id' => '6'],
            ['id' => '280', 'title' => 'گرمدره', 'parent_id' => '6'],
            ['id' => '281', 'title' => 'گلسار', 'parent_id' => '6'],
            ['id' => '282', 'title' => 'ماهدشت', 'parent_id' => '6'],
            ['id' => '283', 'title' => 'محمدشهر', 'parent_id' => '6'],
            ['id' => '284', 'title' => 'مشکين دشت', 'parent_id' => '6'],
            ['id' => '285', 'title' => 'نظرآباد', 'parent_id' => '6'],
            ['id' => '286', 'title' => 'هشتگرد', 'parent_id' => '6'],
            ['id' => '287', 'title' => 'اركواز', 'parent_id' => '7'],
            ['id' => '288', 'title' => 'ايلام', 'parent_id' => '7'],
            ['id' => '289', 'title' => 'ايوان', 'parent_id' => '7'],
            ['id' => '290', 'title' => 'آبدانان', 'parent_id' => '7'],
            ['id' => '291', 'title' => 'آسمان آباد', 'parent_id' => '7'],
            ['id' => '292', 'title' => 'بدره', 'parent_id' => '7'],
            ['id' => '293', 'title' => 'بلاوه', 'parent_id' => '7'],
            ['id' => '294', 'title' => 'پهله', 'parent_id' => '7'],
            ['id' => '295', 'title' => 'توحيد', 'parent_id' => '7'],
            ['id' => '296', 'title' => 'چوار', 'parent_id' => '7'],
            ['id' => '297', 'title' => 'دره شهر', 'parent_id' => '7'],
            ['id' => '298', 'title' => 'دلگشا', 'parent_id' => '7'],
            ['id' => '299', 'title' => 'دهلران', 'parent_id' => '7'],
            ['id' => '300', 'title' => 'زرنه', 'parent_id' => '7'],
            ['id' => '301', 'title' => 'سراب باغ', 'parent_id' => '7'],
            ['id' => '302', 'title' => 'سرابله', 'parent_id' => '7'],
            ['id' => '303', 'title' => 'شباب', 'parent_id' => '7'],
            ['id' => '304', 'title' => 'صالح آباد', 'parent_id' => '7'],
            ['id' => '305', 'title' => 'لومار', 'parent_id' => '7'],
            ['id' => '306', 'title' => 'ماژين', 'parent_id' => '7'],
            ['id' => '307', 'title' => 'مورمورئ', 'parent_id' => '7'],
            ['id' => '308', 'title' => 'موسيان', 'parent_id' => '7'],
            ['id' => '309', 'title' => 'مهر', 'parent_id' => '7'],
            ['id' => '310', 'title' => 'مهران', 'parent_id' => '7'],
            ['id' => '311', 'title' => 'ميمه', 'parent_id' => '7'],
            ['id' => '312', 'title' => 'امام حسن', 'parent_id' => '8'],
            ['id' => '313', 'title' => 'انارستان', 'parent_id' => '8'],
            ['id' => '314', 'title' => 'اهرم', 'parent_id' => '8'],
            ['id' => '315', 'title' => 'آب پخش', 'parent_id' => '8'],
            ['id' => '316', 'title' => 'آباد', 'parent_id' => '8'],
            ['id' => '317', 'title' => 'آبدان', 'parent_id' => '8'],
            ['id' => '318', 'title' => 'بادوله', 'parent_id' => '8'],
            ['id' => '319', 'title' => 'برازجان', 'parent_id' => '8'],
            ['id' => '320', 'title' => 'بردخون', 'parent_id' => '8'],
            ['id' => '321', 'title' => 'بردستان', 'parent_id' => '8'],
            ['id' => '322', 'title' => 'بندردير', 'parent_id' => '8'],
            ['id' => '323', 'title' => 'بندرديلم', 'parent_id' => '8'],
            ['id' => '324', 'title' => 'بندرريگ', 'parent_id' => '8'],
            ['id' => '325', 'title' => 'بندركنگان', 'parent_id' => '8'],
            ['id' => '326', 'title' => 'بندرگناوه', 'parent_id' => '8'],
            ['id' => '327', 'title' => 'بنك', 'parent_id' => '8'],
            ['id' => '328', 'title' => 'بوشکان', 'parent_id' => '8'],
            ['id' => '329', 'title' => 'بوشهر', 'parent_id' => '8'],
            ['id' => '330', 'title' => 'تنگ ارم', 'parent_id' => '8'],
            ['id' => '331', 'title' => 'جم', 'parent_id' => '8'],
            ['id' => '332', 'title' => 'چغادك', 'parent_id' => '8'],
            ['id' => '333', 'title' => 'خارك', 'parent_id' => '8'],
            ['id' => '334', 'title' => 'خورموج', 'parent_id' => '8'],
            ['id' => '335', 'title' => 'دالكي', 'parent_id' => '8'],
            ['id' => '336', 'title' => 'دلوار', 'parent_id' => '8'],
            ['id' => '337', 'title' => 'دوراهک', 'parent_id' => '8'],
            ['id' => '338', 'title' => 'ريز', 'parent_id' => '8'],
            ['id' => '339', 'title' => 'سعد آباد', 'parent_id' => '8'],
            ['id' => '340', 'title' => 'سيراف', 'parent_id' => '8'],
            ['id' => '341', 'title' => 'شبانكاره', 'parent_id' => '8'],
            ['id' => '342', 'title' => 'شنبه', 'parent_id' => '8'],
            ['id' => '343', 'title' => 'عسلويه', 'parent_id' => '8'],
            ['id' => '344', 'title' => 'كاكي', 'parent_id' => '8'],
            ['id' => '345', 'title' => 'كلمه', 'parent_id' => '8'],
            ['id' => '346', 'title' => 'نخل تقي', 'parent_id' => '8'],
            ['id' => '347', 'title' => 'وحدتيه', 'parent_id' => '8'],
            ['id' => '348', 'title' => 'ارجمند', 'parent_id' => '9'],
            ['id' => '349', 'title' => 'اسلامشهر', 'parent_id' => '9'],
            ['id' => '350', 'title' => 'انديشه', 'parent_id' => '9'],
            ['id' => '351', 'title' => 'آبسرد', 'parent_id' => '9'],
            ['id' => '352', 'title' => 'آبعلي', 'parent_id' => '9'],
            ['id' => '353', 'title' => 'باغستان', 'parent_id' => '9'],
            ['id' => '354', 'title' => 'باقرشهر', 'parent_id' => '9'],
            ['id' => '355', 'title' => 'بومهن', 'parent_id' => '9'],
            ['id' => '356', 'title' => 'پاكدشت', 'parent_id' => '9'],
            ['id' => '357', 'title' => 'پرديس', 'parent_id' => '9'],
            ['id' => '358', 'title' => 'پرند', 'parent_id' => '9'],
            ['id' => '359', 'title' => 'پيشوا', 'parent_id' => '9'],
            ['id' => '360', 'title' => 'تجريش', 'parent_id' => '9'],
            ['id' => '361', 'title' => 'تهران', 'parent_id' => '9'],
            ['id' => '362', 'title' => 'جوادآباد', 'parent_id' => '9'],
            ['id' => '363', 'title' => 'چهاردانگه', 'parent_id' => '9'],
            ['id' => '364', 'title' => 'حسن آباد', 'parent_id' => '9'],
            ['id' => '365', 'title' => 'دماوند', 'parent_id' => '9'],
            ['id' => '366', 'title' => 'رباطكريم', 'parent_id' => '9'],
            ['id' => '367', 'title' => 'رودهن', 'parent_id' => '9'],
            ['id' => '368', 'title' => 'رئ', 'parent_id' => '9'],
            ['id' => '369', 'title' => 'شاهدشهر', 'parent_id' => '9'],
            ['id' => '370', 'title' => 'شريف آباد', 'parent_id' => '9'],
            ['id' => '371', 'title' => 'شمشک', 'parent_id' => '9'],
            ['id' => '372', 'title' => 'شهريار', 'parent_id' => '9'],
            ['id' => '373', 'title' => 'صالحيه', 'parent_id' => '9'],
            ['id' => '374', 'title' => 'صباشهر', 'parent_id' => '9'],
            ['id' => '375', 'title' => 'صفادشت', 'parent_id' => '9'],
            ['id' => '376', 'title' => 'فردوسيه', 'parent_id' => '9'],
            ['id' => '377', 'title' => 'فرون اباد', 'parent_id' => '9'],
            ['id' => '378', 'title' => 'فشم', 'parent_id' => '9'],
            ['id' => '379', 'title' => 'فيروزكوه', 'parent_id' => '9'],
            ['id' => '380', 'title' => 'قدس', 'parent_id' => '9'],
            ['id' => '381', 'title' => 'قرچک', 'parent_id' => '9'],
            ['id' => '382', 'title' => 'كهريزك', 'parent_id' => '9'],
            ['id' => '383', 'title' => 'كيلان', 'parent_id' => '9'],
            ['id' => '384', 'title' => 'گلستان', 'parent_id' => '9'],
            ['id' => '385', 'title' => 'لواسان', 'parent_id' => '9'],
            ['id' => '386', 'title' => 'ملارد', 'parent_id' => '9'],
            ['id' => '387', 'title' => 'نسيم شهر', 'parent_id' => '9'],
            ['id' => '388', 'title' => 'نصيرشهر', 'parent_id' => '9'],
            ['id' => '389', 'title' => 'وحيديه', 'parent_id' => '9'],
            ['id' => '390', 'title' => 'ورامين', 'parent_id' => '9'],
            ['id' => '391', 'title' => 'اردل', 'parent_id' => '10'],
            ['id' => '392', 'title' => 'آلوني', 'parent_id' => '10'],
            ['id' => '393', 'title' => 'باباحيدر', 'parent_id' => '10'],
            ['id' => '394', 'title' => 'بازفت', 'parent_id' => '10'],
            ['id' => '395', 'title' => 'بروجن', 'parent_id' => '10'],
            ['id' => '396', 'title' => 'بلداجي', 'parent_id' => '10'],
            ['id' => '397', 'title' => 'بن', 'parent_id' => '10'],
            ['id' => '398', 'title' => 'پردنجان', 'parent_id' => '10'],
            ['id' => '399', 'title' => 'جونقان', 'parent_id' => '10'],
            ['id' => '400', 'title' => 'چلگرد', 'parent_id' => '10'],
            ['id' => '401', 'title' => 'چليچه', 'parent_id' => '10'],
            ['id' => '402', 'title' => 'دستنا', 'parent_id' => '10'],
            ['id' => '403', 'title' => 'دشتک', 'parent_id' => '10'],
            ['id' => '404', 'title' => 'سامان', 'parent_id' => '10'],
            ['id' => '405', 'title' => 'سرخون', 'parent_id' => '10'],
            ['id' => '406', 'title' => 'سردشت', 'parent_id' => '10'],
            ['id' => '407', 'title' => 'سفيددشت', 'parent_id' => '10'],
            ['id' => '408', 'title' => 'سودجان', 'parent_id' => '10'],
            ['id' => '409', 'title' => 'سورشجان', 'parent_id' => '10'],
            ['id' => '410', 'title' => 'شلمزار', 'parent_id' => '10'],
            ['id' => '411', 'title' => 'شهركرد', 'parent_id' => '10'],
            ['id' => '412', 'title' => 'صمصامي', 'parent_id' => '10'],
            ['id' => '413', 'title' => 'طاقانك', 'parent_id' => '10'],
            ['id' => '414', 'title' => 'فارسان', 'parent_id' => '10'],
            ['id' => '415', 'title' => 'فرادبنه', 'parent_id' => '10'],
            ['id' => '416', 'title' => 'فرخ شهر', 'parent_id' => '10'],
            ['id' => '417', 'title' => 'کاج', 'parent_id' => '10'],
            ['id' => '418', 'title' => 'كيان', 'parent_id' => '10'],
            ['id' => '419', 'title' => 'گندمان', 'parent_id' => '10'],
            ['id' => '420', 'title' => 'گوجان', 'parent_id' => '10'],
            ['id' => '421', 'title' => 'گهرو', 'parent_id' => '10'],
            ['id' => '422', 'title' => 'لردگان', 'parent_id' => '10'],
            ['id' => '423', 'title' => 'مال خليفه', 'parent_id' => '10'],
            ['id' => '424', 'title' => 'منج', 'parent_id' => '10'],
            ['id' => '425', 'title' => 'ناغان', 'parent_id' => '10'],
            ['id' => '426', 'title' => 'نافچ', 'parent_id' => '10'],
            ['id' => '427', 'title' => 'نقنه', 'parent_id' => '10'],
            ['id' => '428', 'title' => 'وردنجان', 'parent_id' => '10'],
            ['id' => '429', 'title' => 'هاروني', 'parent_id' => '10'],
            ['id' => '430', 'title' => 'هفشجان', 'parent_id' => '10'],
            ['id' => '431', 'title' => 'ارسك', 'parent_id' => '11'],
            ['id' => '432', 'title' => 'اسديه', 'parent_id' => '11'],
            ['id' => '433', 'title' => 'اسفدن', 'parent_id' => '11'],
            ['id' => '434', 'title' => 'اسلاميه', 'parent_id' => '11'],
            ['id' => '435', 'title' => 'آرين شهر', 'parent_id' => '11'],
            ['id' => '436', 'title' => 'آيسك', 'parent_id' => '11'],
            ['id' => '437', 'title' => 'بشرويه', 'parent_id' => '11'],
            ['id' => '438', 'title' => 'بيرجند', 'parent_id' => '11'],
            ['id' => '439', 'title' => 'حاجي آباد', 'parent_id' => '11'],
            ['id' => '440', 'title' => 'خضرئ دشت بياض', 'parent_id' => '11'],
            ['id' => '441', 'title' => 'خوسف', 'parent_id' => '11'],
            ['id' => '442', 'title' => 'ديهوك', 'parent_id' => '11'],
            ['id' => '443', 'title' => 'زهان', 'parent_id' => '11'],
            ['id' => '444', 'title' => 'سرايان', 'parent_id' => '11'],
            ['id' => '445', 'title' => 'سربيشه', 'parent_id' => '11'],
            ['id' => '446', 'title' => 'سه قلعه', 'parent_id' => '11'],
            ['id' => '447', 'title' => 'شوسف', 'parent_id' => '11'],
            ['id' => '448', 'title' => 'طبس', 'parent_id' => '11'],
            ['id' => '449', 'title' => 'طبس مسينا', 'parent_id' => '11'],
            ['id' => '450', 'title' => 'عشق آباد', 'parent_id' => '11'],
            ['id' => '451', 'title' => 'فردوس', 'parent_id' => '11'],
            ['id' => '452', 'title' => 'قائن', 'parent_id' => '11'],
            ['id' => '453', 'title' => 'قهستان', 'parent_id' => '11'],
            ['id' => '454', 'title' => 'گزيك', 'parent_id' => '11'],
            ['id' => '455', 'title' => 'محمدشهر', 'parent_id' => '11'],
            ['id' => '456', 'title' => 'مود', 'parent_id' => '11'],
            ['id' => '457', 'title' => 'نهبندان', 'parent_id' => '11'],
            ['id' => '458', 'title' => 'نيمبلوك', 'parent_id' => '11'],
            ['id' => '459', 'title' => 'احمدابادصولت', 'parent_id' => '12'],
            ['id' => '460', 'title' => 'انابد', 'parent_id' => '12'],
            ['id' => '461', 'title' => 'باجگيران', 'parent_id' => '12'],
            ['id' => '462', 'title' => 'باخرز', 'parent_id' => '12'],
            ['id' => '463', 'title' => 'بار', 'parent_id' => '12'],
            ['id' => '464', 'title' => 'بايك', 'parent_id' => '12'],
            ['id' => '465', 'title' => 'بجستان', 'parent_id' => '12'],
            ['id' => '466', 'title' => 'بردسكن', 'parent_id' => '12'],
            ['id' => '467', 'title' => 'بيدخت', 'parent_id' => '12'],
            ['id' => '468', 'title' => 'تايباد', 'parent_id' => '12'],
            ['id' => '469', 'title' => 'تربت جام', 'parent_id' => '12'],
            ['id' => '470', 'title' => 'تربت حيدريه', 'parent_id' => '12'],
            ['id' => '471', 'title' => 'جغتائ', 'parent_id' => '12'],
            ['id' => '472', 'title' => 'جنگل', 'parent_id' => '12'],
            ['id' => '473', 'title' => 'چاپشلو', 'parent_id' => '12'],
            ['id' => '474', 'title' => 'چكنه', 'parent_id' => '12'],
            ['id' => '475', 'title' => 'چناران', 'parent_id' => '12'],
            ['id' => '476', 'title' => 'خرو', 'parent_id' => '12'],
            ['id' => '477', 'title' => 'خليل آباد', 'parent_id' => '12'],
            ['id' => '478', 'title' => 'خواف', 'parent_id' => '12'],
            ['id' => '479', 'title' => 'داورزن', 'parent_id' => '12'],
            ['id' => '480', 'title' => 'درگز', 'parent_id' => '12'],
            ['id' => '481', 'title' => 'درود', 'parent_id' => '12'],
            ['id' => '482', 'title' => 'دولت آباد', 'parent_id' => '12'],
            ['id' => '483', 'title' => 'رباط سنگ', 'parent_id' => '12'],
            ['id' => '484', 'title' => 'رشتخوار', 'parent_id' => '12'],
            ['id' => '485', 'title' => 'رضويه', 'parent_id' => '12'],
            ['id' => '486', 'title' => 'روداب', 'parent_id' => '12'],
            ['id' => '487', 'title' => 'ريوش', 'parent_id' => '12'],
            ['id' => '488', 'title' => 'سبزوار', 'parent_id' => '12'],
            ['id' => '489', 'title' => 'سرخس', 'parent_id' => '12'],
            ['id' => '490', 'title' => 'سفيدسنگ', 'parent_id' => '12'],
            ['id' => '491', 'title' => 'سلامي', 'parent_id' => '12'],
            ['id' => '492', 'title' => 'سلطان آباد', 'parent_id' => '12'],
            ['id' => '493', 'title' => 'سنگان', 'parent_id' => '12'],
            ['id' => '494', 'title' => 'شادمهر', 'parent_id' => '12'],
            ['id' => '495', 'title' => 'شانديز', 'parent_id' => '12'],
            ['id' => '496', 'title' => 'ششتمد', 'parent_id' => '12'],
            ['id' => '497', 'title' => 'شهراباد', 'parent_id' => '12'],
            ['id' => '498', 'title' => 'شهرزو', 'parent_id' => '12'],
            ['id' => '499', 'title' => 'صالح آباد', 'parent_id' => '12'],
            ['id' => '500', 'title' => 'طرقبه', 'parent_id' => '12'],
            ['id' => '501', 'title' => 'عشق آباد', 'parent_id' => '12'],
            ['id' => '502', 'title' => 'فرهادگرد', 'parent_id' => '12'],
            ['id' => '503', 'title' => 'فريمان', 'parent_id' => '12'],
            ['id' => '504', 'title' => 'فيروزه', 'parent_id' => '12'],
            ['id' => '505', 'title' => 'فيض آباد', 'parent_id' => '12'],
            ['id' => '506', 'title' => 'قاسم آباد', 'parent_id' => '12'],
            ['id' => '507', 'title' => 'قدمگاه', 'parent_id' => '12'],
            ['id' => '508', 'title' => 'قلندرآباد', 'parent_id' => '12'],
            ['id' => '509', 'title' => 'قوچان', 'parent_id' => '12'],
            ['id' => '510', 'title' => 'كاخك', 'parent_id' => '12'],
            ['id' => '511', 'title' => 'كاريز', 'parent_id' => '12'],
            ['id' => '512', 'title' => 'كاشمر', 'parent_id' => '12'],
            ['id' => '513', 'title' => 'كدكن', 'parent_id' => '12'],
            ['id' => '514', 'title' => 'كلات', 'parent_id' => '12'],
            ['id' => '515', 'title' => 'كندر', 'parent_id' => '12'],
            ['id' => '516', 'title' => 'گلمكان', 'parent_id' => '12'],
            ['id' => '517', 'title' => 'گناباد', 'parent_id' => '12'],
            ['id' => '518', 'title' => 'لطف آباد', 'parent_id' => '12'],
            ['id' => '519', 'title' => 'مزدآوند', 'parent_id' => '12'],
            ['id' => '520', 'title' => 'مشهد', 'parent_id' => '12'],
            ['id' => '521', 'title' => 'مشهدريزه', 'parent_id' => '12'],
            ['id' => '522', 'title' => 'ملك آباد', 'parent_id' => '12'],
            ['id' => '523', 'title' => 'نشتيفان', 'parent_id' => '12'],
            ['id' => '524', 'title' => 'نصرآباد', 'parent_id' => '12'],
            ['id' => '525', 'title' => 'نقاب', 'parent_id' => '12'],
            ['id' => '526', 'title' => 'نوخندان', 'parent_id' => '12'],
            ['id' => '527', 'title' => 'نيشابور', 'parent_id' => '12'],
            ['id' => '528', 'title' => 'نيل شهر', 'parent_id' => '12'],
            ['id' => '529', 'title' => 'همت آباد', 'parent_id' => '12'],
            ['id' => '530', 'title' => 'يونسي', 'parent_id' => '12'],
            ['id' => '531', 'title' => 'اسفراين', 'parent_id' => '13'],
            ['id' => '532', 'title' => 'ايور', 'parent_id' => '13'],
            ['id' => '533', 'title' => 'آشخانه', 'parent_id' => '13'],
            ['id' => '534', 'title' => 'آوا', 'parent_id' => '13'],
            ['id' => '535', 'title' => 'بجنورد', 'parent_id' => '13'],
            ['id' => '536', 'title' => 'پيش قلعه', 'parent_id' => '13'],
            ['id' => '537', 'title' => 'تيتكانلو', 'parent_id' => '13'],
            ['id' => '538', 'title' => 'جاجرم', 'parent_id' => '13'],
            ['id' => '539', 'title' => 'چناران شهر', 'parent_id' => '13'],
            ['id' => '540', 'title' => 'حصارگرمخان', 'parent_id' => '13'],
            ['id' => '541', 'title' => 'درق', 'parent_id' => '13'],
            ['id' => '542', 'title' => 'راز', 'parent_id' => '13'],
            ['id' => '543', 'title' => 'زيارت', 'parent_id' => '13'],
            ['id' => '544', 'title' => 'سنخواست', 'parent_id' => '13'],
            ['id' => '545', 'title' => 'شوقان', 'parent_id' => '13'],
            ['id' => '546', 'title' => 'شيروان', 'parent_id' => '13'],
            ['id' => '547', 'title' => 'صفي آباد', 'parent_id' => '13'],
            ['id' => '548', 'title' => 'فاروج', 'parent_id' => '13'],
            ['id' => '549', 'title' => 'قاضي', 'parent_id' => '13'],
            ['id' => '550', 'title' => 'قوشخانه', 'parent_id' => '13'],
            ['id' => '551', 'title' => 'گرمه', 'parent_id' => '13'],
            ['id' => '552', 'title' => 'لوجلي', 'parent_id' => '13'],
            ['id' => '553', 'title' => 'ابوحميظه', 'parent_id' => '14'],
            ['id' => '554', 'title' => 'اروندکنار', 'parent_id' => '14'],
            ['id' => '555', 'title' => 'الوان', 'parent_id' => '14'],
            ['id' => '556', 'title' => 'الهايي', 'parent_id' => '14'],
            ['id' => '557', 'title' => 'اميديه', 'parent_id' => '14'],
            ['id' => '558', 'title' => 'انديمشک', 'parent_id' => '14'],
            ['id' => '559', 'title' => 'اهواز', 'parent_id' => '14'],
            ['id' => '560', 'title' => 'ايذه', 'parent_id' => '14'],
            ['id' => '561', 'title' => 'آبادان', 'parent_id' => '14'],
            ['id' => '562', 'title' => 'آبژدان', 'parent_id' => '14'],
            ['id' => '563', 'title' => 'آزادي', 'parent_id' => '14'],
            ['id' => '564', 'title' => 'آغاجاري', 'parent_id' => '14'],
            ['id' => '565', 'title' => 'باغ ملک', 'parent_id' => '14'],
            ['id' => '566', 'title' => 'بستان', 'parent_id' => '14'],
            ['id' => '567', 'title' => 'بندرامام خميني', 'parent_id' => '14'],
            ['id' => '568', 'title' => 'بندرماهشهر', 'parent_id' => '14'],
            ['id' => '569', 'title' => 'بهبهان', 'parent_id' => '14'],
            ['id' => '570', 'title' => 'بيدروبه', 'parent_id' => '14'],
            ['id' => '571', 'title' => 'ترکالکي', 'parent_id' => '14'],
            ['id' => '572', 'title' => 'تشان', 'parent_id' => '14'],
            ['id' => '573', 'title' => 'جايزان', 'parent_id' => '14'],
            ['id' => '574', 'title' => 'جنت مکان', 'parent_id' => '14'],
            ['id' => '575', 'title' => 'چغاميش', 'parent_id' => '14'],
            ['id' => '576', 'title' => 'چم گلک', 'parent_id' => '14'],
            ['id' => '577', 'title' => 'چمران', 'parent_id' => '14'],
            ['id' => '578', 'title' => 'چويبده', 'parent_id' => '14'],
            ['id' => '579', 'title' => 'حر', 'parent_id' => '14'],
            ['id' => '580', 'title' => 'حسينيه', 'parent_id' => '14'],
            ['id' => '581', 'title' => 'حمزه', 'parent_id' => '14'],
            ['id' => '582', 'title' => 'حميديه', 'parent_id' => '14'],
            ['id' => '583', 'title' => 'خرمشهر', 'parent_id' => '14'],
            ['id' => '584', 'title' => 'خنافره', 'parent_id' => '14'],
            ['id' => '585', 'title' => 'دارخوين', 'parent_id' => '14'],
            ['id' => '586', 'title' => 'دزفول', 'parent_id' => '14'],
            ['id' => '587', 'title' => 'دهدز', 'parent_id' => '14'],
            ['id' => '588', 'title' => 'رامشير', 'parent_id' => '14'],
            ['id' => '589', 'title' => 'رامهرمز', 'parent_id' => '14'],
            ['id' => '590', 'title' => 'رفيع', 'parent_id' => '14'],
            ['id' => '591', 'title' => 'زهره', 'parent_id' => '14'],
            ['id' => '592', 'title' => 'سالند', 'parent_id' => '14'],
            ['id' => '593', 'title' => 'سرداران', 'parent_id' => '14'],
            ['id' => '594', 'title' => 'سردشت', 'parent_id' => '14'],
            ['id' => '595', 'title' => 'سماله', 'parent_id' => '14'],
            ['id' => '596', 'title' => 'سوسنگرد', 'parent_id' => '14'],
            ['id' => '597', 'title' => 'سياه منصور', 'parent_id' => '14'],
            ['id' => '598', 'title' => 'شادگان', 'parent_id' => '14'],
            ['id' => '599', 'title' => 'شاوور', 'parent_id' => '14'],
            ['id' => '600', 'title' => 'شرافت', 'parent_id' => '14'],
            ['id' => '601', 'title' => 'شمس آباد', 'parent_id' => '14'],
            ['id' => '602', 'title' => 'شوش', 'parent_id' => '14'],
            ['id' => '603', 'title' => 'شوشتر', 'parent_id' => '14'],
            ['id' => '604', 'title' => 'شهر امام', 'parent_id' => '14'],
            ['id' => '605', 'title' => 'شيبان', 'parent_id' => '14'],
            ['id' => '606', 'title' => 'صالح شهر', 'parent_id' => '14'],
            ['id' => '607', 'title' => 'صفي آباد', 'parent_id' => '14'],
            ['id' => '608', 'title' => 'صيدون', 'parent_id' => '14'],
            ['id' => '609', 'title' => 'فتح المبين', 'parent_id' => '14'],
            ['id' => '610', 'title' => 'قلعه تل', 'parent_id' => '14'],
            ['id' => '611', 'title' => 'قلعه خواجه', 'parent_id' => '14'],
            ['id' => '612', 'title' => 'کوت سيدنعيم', 'parent_id' => '14'],
            ['id' => '613', 'title' => 'کوت عبداله', 'parent_id' => '14'],
            ['id' => '614', 'title' => 'گتوند', 'parent_id' => '14'],
            ['id' => '615', 'title' => 'گلگير', 'parent_id' => '14'],
            ['id' => '616', 'title' => 'گوريه', 'parent_id' => '14'],
            ['id' => '617', 'title' => 'لالي', 'parent_id' => '14'],
            ['id' => '618', 'title' => 'مسجدسليمان', 'parent_id' => '14'],
            ['id' => '619', 'title' => 'مشراگه', 'parent_id' => '14'],
            ['id' => '620', 'title' => 'مقاومت', 'parent_id' => '14'],
            ['id' => '621', 'title' => 'ملاثاني', 'parent_id' => '14'],
            ['id' => '622', 'title' => 'منصوريه', 'parent_id' => '14'],
            ['id' => '623', 'title' => 'ميانرود', 'parent_id' => '14'],
            ['id' => '624', 'title' => 'ميداود', 'parent_id' => '14'],
            ['id' => '625', 'title' => 'مينوشهر', 'parent_id' => '14'],
            ['id' => '626', 'title' => 'ويس', 'parent_id' => '14'],
            ['id' => '627', 'title' => 'هفتگل', 'parent_id' => '14'],
            ['id' => '628', 'title' => 'هنديجان', 'parent_id' => '14'],
            ['id' => '629', 'title' => 'هويزه', 'parent_id' => '14'],
            ['id' => '630', 'title' => 'ابهر', 'parent_id' => '15'],
            ['id' => '631', 'title' => 'ارمغانخانه', 'parent_id' => '15'],
            ['id' => '632', 'title' => 'آب بر', 'parent_id' => '15'],
            ['id' => '633', 'title' => 'چورزق', 'parent_id' => '15'],
            ['id' => '634', 'title' => 'حلب', 'parent_id' => '15'],
            ['id' => '635', 'title' => 'خرمدره', 'parent_id' => '15'],
            ['id' => '636', 'title' => 'دندي', 'parent_id' => '15'],
            ['id' => '637', 'title' => 'زرين آباد', 'parent_id' => '15'],
            ['id' => '638', 'title' => 'زرين رود', 'parent_id' => '15'],
            ['id' => '639', 'title' => 'زنجان', 'parent_id' => '15'],
            ['id' => '640', 'title' => 'سجاس', 'parent_id' => '15'],
            ['id' => '641', 'title' => 'سلطانيه', 'parent_id' => '15'],
            ['id' => '642', 'title' => 'سهرورد', 'parent_id' => '15'],
            ['id' => '643', 'title' => 'صايين قلعه', 'parent_id' => '15'],
            ['id' => '644', 'title' => 'قيدار', 'parent_id' => '15'],
            ['id' => '645', 'title' => 'کرسف', 'parent_id' => '15'],
            ['id' => '646', 'title' => 'گرماب', 'parent_id' => '15'],
            ['id' => '647', 'title' => 'ماه نشان', 'parent_id' => '15'],
            ['id' => '648', 'title' => 'نوربهار', 'parent_id' => '15'],
            ['id' => '649', 'title' => 'نيک پي', 'parent_id' => '15'],
            ['id' => '650', 'title' => 'هيدج', 'parent_id' => '15'],
            ['id' => '651', 'title' => 'اميريه', 'parent_id' => '16'],
            ['id' => '652', 'title' => 'ايوانكي', 'parent_id' => '16'],
            ['id' => '653', 'title' => 'آرادان', 'parent_id' => '16'],
            ['id' => '654', 'title' => 'بسطام', 'parent_id' => '16'],
            ['id' => '655', 'title' => 'بيارجمند', 'parent_id' => '16'],
            ['id' => '656', 'title' => 'دامغان', 'parent_id' => '16'],
            ['id' => '657', 'title' => 'درجزين', 'parent_id' => '16'],
            ['id' => '658', 'title' => 'ديباج', 'parent_id' => '16'],
            ['id' => '659', 'title' => 'روديان', 'parent_id' => '16'],
            ['id' => '660', 'title' => 'سرخه', 'parent_id' => '16'],
            ['id' => '661', 'title' => 'سمنان', 'parent_id' => '16'],
            ['id' => '662', 'title' => 'شاهرود', 'parent_id' => '16'],
            ['id' => '663', 'title' => 'شهميرزاد', 'parent_id' => '16'],
            ['id' => '664', 'title' => 'کلاته', 'parent_id' => '16'],
            ['id' => '665', 'title' => 'کهن آباد', 'parent_id' => '16'],
            ['id' => '666', 'title' => 'كلاته خيج', 'parent_id' => '16'],
            ['id' => '667', 'title' => 'گرمسار', 'parent_id' => '16'],
            ['id' => '668', 'title' => 'مجن', 'parent_id' => '16'],
            ['id' => '669', 'title' => 'مهدئ شهر', 'parent_id' => '16'],
            ['id' => '670', 'title' => 'ميامي', 'parent_id' => '16'],
            ['id' => '671', 'title' => 'اديمي', 'parent_id' => '17'],
            ['id' => '672', 'title' => 'اسپكه', 'parent_id' => '17'],
            ['id' => '673', 'title' => 'ايرانشهر', 'parent_id' => '17'],
            ['id' => '674', 'title' => 'بزمان', 'parent_id' => '17'],
            ['id' => '675', 'title' => 'بمپور', 'parent_id' => '17'],
            ['id' => '676', 'title' => 'بنت', 'parent_id' => '17'],
            ['id' => '677', 'title' => 'بنجار', 'parent_id' => '17'],
            ['id' => '678', 'title' => 'پيشين', 'parent_id' => '17'],
            ['id' => '679', 'title' => 'جالق', 'parent_id' => '17'],
            ['id' => '680', 'title' => 'چاه بهار', 'parent_id' => '17'],
            ['id' => '681', 'title' => 'خاش', 'parent_id' => '17'],
            ['id' => '682', 'title' => 'دوست محمد', 'parent_id' => '17'],
            ['id' => '683', 'title' => 'راسك', 'parent_id' => '17'],
            ['id' => '684', 'title' => 'زابل', 'parent_id' => '17'],
            ['id' => '685', 'title' => 'زابلي', 'parent_id' => '17'],
            ['id' => '686', 'title' => 'زاهدان', 'parent_id' => '17'],
            ['id' => '687', 'title' => 'زرآباد', 'parent_id' => '17'],
            ['id' => '688', 'title' => 'زهك', 'parent_id' => '17'],
            ['id' => '689', 'title' => 'سراوان', 'parent_id' => '17'],
            ['id' => '690', 'title' => 'سرباز', 'parent_id' => '17'],
            ['id' => '691', 'title' => 'سوران', 'parent_id' => '17'],
            ['id' => '692', 'title' => 'سيركان', 'parent_id' => '17'],
            ['id' => '693', 'title' => 'علي اکبر', 'parent_id' => '17'],
            ['id' => '694', 'title' => 'فنوج', 'parent_id' => '17'],
            ['id' => '695', 'title' => 'قصرقند', 'parent_id' => '17'],
            ['id' => '696', 'title' => 'كنارك', 'parent_id' => '17'],
            ['id' => '697', 'title' => 'گشت', 'parent_id' => '17'],
            ['id' => '698', 'title' => 'گلمورتي', 'parent_id' => '17'],
            ['id' => '699', 'title' => 'محمدان', 'parent_id' => '17'],
            ['id' => '700', 'title' => 'محمدآباد', 'parent_id' => '17'],
            ['id' => '701', 'title' => 'محمدي', 'parent_id' => '17'],
            ['id' => '702', 'title' => 'ميرجاوه', 'parent_id' => '17'],
            ['id' => '703', 'title' => 'نصرت آباد', 'parent_id' => '17'],
            ['id' => '704', 'title' => 'نگور', 'parent_id' => '17'],
            ['id' => '705', 'title' => 'نوك آباد', 'parent_id' => '17'],
            ['id' => '706', 'title' => 'نيك شهر', 'parent_id' => '17'],
            ['id' => '707', 'title' => 'هيدوچ', 'parent_id' => '17'],
            ['id' => '708', 'title' => 'اردکان', 'parent_id' => '18'],
            ['id' => '709', 'title' => 'ارسنجان', 'parent_id' => '18'],
            ['id' => '710', 'title' => 'استهبان', 'parent_id' => '18'],
            ['id' => '711', 'title' => 'اسير', 'parent_id' => '18'],
            ['id' => '712', 'title' => 'اشکنان', 'parent_id' => '18'],
            ['id' => '713', 'title' => 'افزر', 'parent_id' => '18'],
            ['id' => '714', 'title' => 'اقليد', 'parent_id' => '18'],
            ['id' => '715', 'title' => 'امام شهر', 'parent_id' => '18'],
            ['id' => '716', 'title' => 'اوز', 'parent_id' => '18'],
            ['id' => '717', 'title' => 'اهل', 'parent_id' => '18'],
            ['id' => '718', 'title' => 'ايج', 'parent_id' => '18'],
            ['id' => '719', 'title' => 'ايزدخواست', 'parent_id' => '18'],
            ['id' => '720', 'title' => 'آباده', 'parent_id' => '18'],
            ['id' => '721', 'title' => 'آباده طشک', 'parent_id' => '18'],
            ['id' => '722', 'title' => 'باب انار', 'parent_id' => '18'],
            ['id' => '723', 'title' => 'بابامنير', 'parent_id' => '18'],
            ['id' => '724', 'title' => 'بالاده', 'parent_id' => '18'],
            ['id' => '725', 'title' => 'بنارويه', 'parent_id' => '18'],
            ['id' => '726', 'title' => 'بوانات', 'parent_id' => '18'],
            ['id' => '727', 'title' => 'بهمن', 'parent_id' => '18'],
            ['id' => '728', 'title' => 'بيرم', 'parent_id' => '18'],
            ['id' => '729', 'title' => 'بيضا', 'parent_id' => '18'],
            ['id' => '730', 'title' => 'جنت شهر', 'parent_id' => '18'],
            ['id' => '731', 'title' => 'جويم', 'parent_id' => '18'],
            ['id' => '732', 'title' => 'جهرم', 'parent_id' => '18'],
            ['id' => '733', 'title' => 'حاجي آباد', 'parent_id' => '18'],
            ['id' => '734', 'title' => 'حسامي', 'parent_id' => '18'],
            ['id' => '735', 'title' => 'حسن اباد', 'parent_id' => '18'],
            ['id' => '736', 'title' => 'خانه زنيان', 'parent_id' => '18'],
            ['id' => '737', 'title' => 'خانيمن', 'parent_id' => '18'],
            ['id' => '738', 'title' => 'خاوران', 'parent_id' => '18'],
            ['id' => '739', 'title' => 'خرامه', 'parent_id' => '18'],
            ['id' => '740', 'title' => 'خشت', 'parent_id' => '18'],
            ['id' => '741', 'title' => 'خنج', 'parent_id' => '18'],
            ['id' => '742', 'title' => 'خور', 'parent_id' => '18'],
            ['id' => '743', 'title' => 'خوزي', 'parent_id' => '18'],
            ['id' => '744', 'title' => 'خومه زار', 'parent_id' => '18'],
            ['id' => '745', 'title' => 'داراب', 'parent_id' => '18'],
            ['id' => '746', 'title' => 'داريان', 'parent_id' => '18'],
            ['id' => '747', 'title' => 'دبيران', 'parent_id' => '18'],
            ['id' => '748', 'title' => 'دژکرد', 'parent_id' => '18'],
            ['id' => '749', 'title' => 'دوبرجي', 'parent_id' => '18'],
            ['id' => '750', 'title' => 'دوزه', 'parent_id' => '18'],
            ['id' => '751', 'title' => 'دهرم', 'parent_id' => '18'],
            ['id' => '752', 'title' => 'رامجرد', 'parent_id' => '18'],
            ['id' => '753', 'title' => 'رونيز', 'parent_id' => '18'],
            ['id' => '754', 'title' => 'زاهدشهر', 'parent_id' => '18'],
            ['id' => '755', 'title' => 'زرقان', 'parent_id' => '18'],
            ['id' => '756', 'title' => 'سده', 'parent_id' => '18'],
            ['id' => '757', 'title' => 'سروستان', 'parent_id' => '18'],
            ['id' => '758', 'title' => 'سعادت شهر', 'parent_id' => '18'],
            ['id' => '759', 'title' => 'سلطان شهر', 'parent_id' => '18'],
            ['id' => '760', 'title' => 'سورمق', 'parent_id' => '18'],
            ['id' => '761', 'title' => 'سيدان', 'parent_id' => '18'],
            ['id' => '762', 'title' => 'ششده', 'parent_id' => '18'],
            ['id' => '763', 'title' => 'شهرپير', 'parent_id' => '18'],
            ['id' => '764', 'title' => 'شهرصدرا', 'parent_id' => '18'],
            ['id' => '765', 'title' => 'شيراز', 'parent_id' => '18'],
            ['id' => '766', 'title' => 'صغاد', 'parent_id' => '18'],
            ['id' => '767', 'title' => 'صفاشهر', 'parent_id' => '18'],
            ['id' => '768', 'title' => 'علامرودشت', 'parent_id' => '18'],
            ['id' => '769', 'title' => 'عمادده', 'parent_id' => '18'],
            ['id' => '770', 'title' => 'فدامي', 'parent_id' => '18'],
            ['id' => '771', 'title' => 'فراشبند', 'parent_id' => '18'],
            ['id' => '772', 'title' => 'فسا', 'parent_id' => '18'],
            ['id' => '773', 'title' => 'فيروزآباد', 'parent_id' => '18'],
            ['id' => '774', 'title' => 'قادراباد', 'parent_id' => '18'],
            ['id' => '775', 'title' => 'قايميه', 'parent_id' => '18'],
            ['id' => '776', 'title' => 'قره بلاغ', 'parent_id' => '18'],
            ['id' => '777', 'title' => 'قطب آباد', 'parent_id' => '18'],
            ['id' => '778', 'title' => 'قطرويه', 'parent_id' => '18'],
            ['id' => '779', 'title' => 'قير', 'parent_id' => '18'],
            ['id' => '780', 'title' => 'کارزين (فتح آباد]', 'parent_id' => '18'],
            ['id' => '781', 'title' => 'کازرون', 'parent_id' => '18'],
            ['id' => '782', 'title' => 'کامفيروز', 'parent_id' => '18'],
            ['id' => '783', 'title' => 'کره اي', 'parent_id' => '18'],
            ['id' => '784', 'title' => 'کنارتخته', 'parent_id' => '18'],
            ['id' => '785', 'title' => 'کوار', 'parent_id' => '18'],
            ['id' => '786', 'title' => 'کوپن', 'parent_id' => '18'],
            ['id' => '787', 'title' => 'کوهنجان', 'parent_id' => '18'],
            ['id' => '788', 'title' => 'گراش', 'parent_id' => '18'],
            ['id' => '789', 'title' => 'گله دار', 'parent_id' => '18'],
            ['id' => '790', 'title' => 'لار', 'parent_id' => '18'],
            ['id' => '791', 'title' => 'لامرد', 'parent_id' => '18'],
            ['id' => '792', 'title' => 'لپويي', 'parent_id' => '18'],
            ['id' => '793', 'title' => 'لطيفي', 'parent_id' => '18'],
            ['id' => '794', 'title' => 'مادرسليمان', 'parent_id' => '18'],
            ['id' => '795', 'title' => 'مبارک آبادديز', 'parent_id' => '18'],
            ['id' => '796', 'title' => 'مرودشت', 'parent_id' => '18'],
            ['id' => '797', 'title' => 'مزايجان', 'parent_id' => '18'],
            ['id' => '798', 'title' => 'مشکان', 'parent_id' => '18'],
            ['id' => '799', 'title' => 'مصيري', 'parent_id' => '18'],
            ['id' => '800', 'title' => 'مهر', 'parent_id' => '18'],
            ['id' => '801', 'title' => 'ميانشهر', 'parent_id' => '18'],
            ['id' => '802', 'title' => 'ميمند', 'parent_id' => '18'],
            ['id' => '803', 'title' => 'نوبندگان', 'parent_id' => '18'],
            ['id' => '804', 'title' => 'نوجين', 'parent_id' => '18'],
            ['id' => '805', 'title' => 'نودان', 'parent_id' => '18'],
            ['id' => '806', 'title' => 'نورآباد', 'parent_id' => '18'],
            ['id' => '807', 'title' => 'ني ريز', 'parent_id' => '18'],
            ['id' => '808', 'title' => 'وراوي', 'parent_id' => '18'],
            ['id' => '809', 'title' => 'هماشهر', 'parent_id' => '18'],
            ['id' => '810', 'title' => 'ارداق', 'parent_id' => '19'],
            ['id' => '811', 'title' => 'اسفرورين', 'parent_id' => '19'],
            ['id' => '812', 'title' => 'اقباليه', 'parent_id' => '19'],
            ['id' => '813', 'title' => 'الوند', 'parent_id' => '19'],
            ['id' => '814', 'title' => 'آبگرم', 'parent_id' => '19'],
            ['id' => '815', 'title' => 'آبيك', 'parent_id' => '19'],
            ['id' => '816', 'title' => 'آوج', 'parent_id' => '19'],
            ['id' => '817', 'title' => 'بوئين زهرا', 'parent_id' => '19'],
            ['id' => '818', 'title' => 'بيدستان', 'parent_id' => '19'],
            ['id' => '819', 'title' => 'تاكستان', 'parent_id' => '19'],
            ['id' => '820', 'title' => 'خاكعلي', 'parent_id' => '19'],
            ['id' => '821', 'title' => 'خرمدشت', 'parent_id' => '19'],
            ['id' => '822', 'title' => 'دانسفهان', 'parent_id' => '19'],
            ['id' => '823', 'title' => 'رازميان', 'parent_id' => '19'],
            ['id' => '824', 'title' => 'سگزآباد', 'parent_id' => '19'],
            ['id' => '825', 'title' => 'سيردان', 'parent_id' => '19'],
            ['id' => '826', 'title' => 'شال', 'parent_id' => '19'],
            ['id' => '827', 'title' => 'شريفيه', 'parent_id' => '19'],
            ['id' => '828', 'title' => 'ضياڈآباد', 'parent_id' => '19'],
            ['id' => '829', 'title' => 'قزوين', 'parent_id' => '19'],
            ['id' => '830', 'title' => 'كوهين', 'parent_id' => '19'],
            ['id' => '831', 'title' => 'محمديه', 'parent_id' => '19'],
            ['id' => '832', 'title' => 'محمودآبادنمونه', 'parent_id' => '19'],
            ['id' => '833', 'title' => 'معلم كلايه', 'parent_id' => '19'],
            ['id' => '834', 'title' => 'نرجه', 'parent_id' => '19'],
            ['id' => '835', 'title' => 'جعفريه', 'parent_id' => '20'],
            ['id' => '836', 'title' => 'دستجرد', 'parent_id' => '20'],
            ['id' => '837', 'title' => 'سلفچگان', 'parent_id' => '20'],
            ['id' => '838', 'title' => 'قم', 'parent_id' => '20'],
            ['id' => '839', 'title' => 'قنوات', 'parent_id' => '20'],
            ['id' => '840', 'title' => 'کهک', 'parent_id' => '20'],
            ['id' => '841', 'title' => 'بانه', 'parent_id' => '21'],
            ['id' => '842', 'title' => 'بیجار', 'parent_id' => '21'],
            ['id' => '843', 'title' => 'دهگلان', 'parent_id' => '21'],
            ['id' => '844', 'title' => 'دیواندره', 'parent_id' => '21'],
            ['id' => '845', 'title' => 'سرو آباد', 'parent_id' => '21'],
            ['id' => '846', 'title' => 'سقز', 'parent_id' => '21'],
            ['id' => '847', 'title' => 'اختيارآباد', 'parent_id' => '22'],
            ['id' => '848', 'title' => 'ارزوئيه', 'parent_id' => '22'],
            ['id' => '849', 'title' => 'امين شهر', 'parent_id' => '22'],
            ['id' => '850', 'title' => 'انار', 'parent_id' => '22'],
            ['id' => '851', 'title' => 'اندوهجرد', 'parent_id' => '22'],
            ['id' => '852', 'title' => 'باغين', 'parent_id' => '22'],
            ['id' => '853', 'title' => 'بافت', 'parent_id' => '22'],
            ['id' => '854', 'title' => 'بردسير', 'parent_id' => '22'],
            ['id' => '855', 'title' => 'بروات', 'parent_id' => '22'],
            ['id' => '856', 'title' => 'بزنجان', 'parent_id' => '22'],
            ['id' => '857', 'title' => 'بلورد', 'parent_id' => '22'],
            ['id' => '858', 'title' => 'بلوک', 'parent_id' => '22'],
            ['id' => '859', 'title' => 'بم', 'parent_id' => '22'],
            ['id' => '860', 'title' => 'بهرمان', 'parent_id' => '22'],
            ['id' => '861', 'title' => 'پاريز', 'parent_id' => '22'],
            ['id' => '862', 'title' => 'جبالبارز', 'parent_id' => '22'],
            ['id' => '863', 'title' => 'جوپار', 'parent_id' => '22'],
            ['id' => '864', 'title' => 'جوزم', 'parent_id' => '22'],
            ['id' => '865', 'title' => 'جيرفت', 'parent_id' => '22'],
            ['id' => '866', 'title' => 'چترود', 'parent_id' => '22'],
            ['id' => '867', 'title' => 'خاتون اباد', 'parent_id' => '22'],
            ['id' => '868', 'title' => 'خانوك', 'parent_id' => '22'],
            ['id' => '869', 'title' => 'خواجو شهر', 'parent_id' => '22'],
            ['id' => '870', 'title' => 'خورسند', 'parent_id' => '22'],
            ['id' => '871', 'title' => 'درب بهشت', 'parent_id' => '22'],
            ['id' => '872', 'title' => 'دشتکار', 'parent_id' => '22'],
            ['id' => '873', 'title' => 'دوساري', 'parent_id' => '22'],
            ['id' => '874', 'title' => 'دهج', 'parent_id' => '22'],
            ['id' => '875', 'title' => 'رابر', 'parent_id' => '22'],
            ['id' => '876', 'title' => 'راور', 'parent_id' => '22'],
            ['id' => '877', 'title' => 'راين', 'parent_id' => '22'],
            ['id' => '878', 'title' => 'رفسنجان', 'parent_id' => '22'],
            ['id' => '879', 'title' => 'رودبار', 'parent_id' => '22'],
            ['id' => '880', 'title' => 'ريحان', 'parent_id' => '22'],
            ['id' => '881', 'title' => 'زرند', 'parent_id' => '22'],
            ['id' => '882', 'title' => 'زنگي آباد', 'parent_id' => '22'],
            ['id' => '883', 'title' => 'زهکلوت', 'parent_id' => '22'],
            ['id' => '884', 'title' => 'زيدآباد', 'parent_id' => '22'],
            ['id' => '885', 'title' => 'سيرجان', 'parent_id' => '22'],
            ['id' => '886', 'title' => 'شهداد', 'parent_id' => '22'],
            ['id' => '887', 'title' => 'شهربابك', 'parent_id' => '22'],
            ['id' => '888', 'title' => 'صفائيه', 'parent_id' => '22'],
            ['id' => '889', 'title' => 'عنبرآباد', 'parent_id' => '22'],
            ['id' => '890', 'title' => 'فارياب', 'parent_id' => '22'],
            ['id' => '891', 'title' => 'فهرج', 'parent_id' => '22'],
            ['id' => '892', 'title' => 'قلعه گنج', 'parent_id' => '22'],
            ['id' => '893', 'title' => 'كاظم آباد', 'parent_id' => '22'],
            ['id' => '894', 'title' => 'كرمان', 'parent_id' => '22'],
            ['id' => '895', 'title' => 'كشكوئيه', 'parent_id' => '22'],
            ['id' => '896', 'title' => 'كوهبنان', 'parent_id' => '22'],
            ['id' => '897', 'title' => 'كهنوج', 'parent_id' => '22'],
            ['id' => '898', 'title' => 'كيانشهر', 'parent_id' => '22'],
            ['id' => '899', 'title' => 'گلباف', 'parent_id' => '22'],
            ['id' => '900', 'title' => 'گلزار', 'parent_id' => '22'],
            ['id' => '901', 'title' => 'گنبکي', 'parent_id' => '22'],
            ['id' => '902', 'title' => 'لاله زار', 'parent_id' => '22'],
            ['id' => '903', 'title' => 'ماهان', 'parent_id' => '22'],
            ['id' => '904', 'title' => 'محمدآباد', 'parent_id' => '22'],
            ['id' => '905', 'title' => 'محي آباد', 'parent_id' => '22'],
            ['id' => '906', 'title' => 'مردهك', 'parent_id' => '22'],
            ['id' => '907', 'title' => 'مس سرچشمه', 'parent_id' => '22'],
            ['id' => '908', 'title' => 'منوجان', 'parent_id' => '22'],
            ['id' => '909', 'title' => 'نجف شهر', 'parent_id' => '22'],
            ['id' => '910', 'title' => 'نرماشير', 'parent_id' => '22'],
            ['id' => '911', 'title' => 'نظام شهر', 'parent_id' => '22'],
            ['id' => '912', 'title' => 'نگار', 'parent_id' => '22'],
            ['id' => '913', 'title' => 'نودژ', 'parent_id' => '22'],
            ['id' => '914', 'title' => 'هجدك', 'parent_id' => '22'],
            ['id' => '915', 'title' => 'هماشهر', 'parent_id' => '22'],
            ['id' => '916', 'title' => 'هنزا', 'parent_id' => '22'],
            ['id' => '917', 'title' => 'يزدان شهر', 'parent_id' => '22'],
            ['id' => '918', 'title' => 'ازگله', 'parent_id' => '23'],
            ['id' => '919', 'title' => 'اسلام آبادغرب', 'parent_id' => '23'],
            ['id' => '920', 'title' => 'بانوره', 'parent_id' => '23'],
            ['id' => '921', 'title' => 'باينگان', 'parent_id' => '23'],
            ['id' => '922', 'title' => 'بيستون', 'parent_id' => '23'],
            ['id' => '923', 'title' => 'پاوه', 'parent_id' => '23'],
            ['id' => '924', 'title' => 'تازه آباد', 'parent_id' => '23'],
            ['id' => '925', 'title' => 'جوانرود', 'parent_id' => '23'],
            ['id' => '926', 'title' => 'حميل', 'parent_id' => '23'],
            ['id' => '927', 'title' => 'رباط', 'parent_id' => '23'],
            ['id' => '928', 'title' => 'روانسر', 'parent_id' => '23'],
            ['id' => '929', 'title' => 'ريجاب', 'parent_id' => '23'],
            ['id' => '930', 'title' => 'سرپل ذهاب', 'parent_id' => '23'],
            ['id' => '931', 'title' => 'سرمست', 'parent_id' => '23'],
            ['id' => '932', 'title' => 'سطر', 'parent_id' => '23'],
            ['id' => '933', 'title' => 'سنقر', 'parent_id' => '23'],
            ['id' => '934', 'title' => 'سومار', 'parent_id' => '23'],
            ['id' => '935', 'title' => 'شاهو', 'parent_id' => '23'],
            ['id' => '936', 'title' => 'صحنه', 'parent_id' => '23'],
            ['id' => '937', 'title' => 'قصرشيرين', 'parent_id' => '23'],
            ['id' => '938', 'title' => 'کرمانشاه', 'parent_id' => '23'],
            ['id' => '939', 'title' => 'کرند', 'parent_id' => '23'],
            ['id' => '940', 'title' => 'کنگاور', 'parent_id' => '23'],
            ['id' => '941', 'title' => 'کوزران', 'parent_id' => '23'],
            ['id' => '942', 'title' => 'گودين', 'parent_id' => '23'],
            ['id' => '943', 'title' => 'گهواره', 'parent_id' => '23'],
            ['id' => '944', 'title' => 'گيلانغرب', 'parent_id' => '23'],
            ['id' => '945', 'title' => 'ميان راهان', 'parent_id' => '23'],
            ['id' => '946', 'title' => 'نودشه', 'parent_id' => '23'],
            ['id' => '947', 'title' => 'نوسود', 'parent_id' => '23'],
            ['id' => '948', 'title' => 'هرسين', 'parent_id' => '23'],
            ['id' => '949', 'title' => 'هلشي', 'parent_id' => '23'],
            ['id' => '950', 'title' => 'باشت', 'parent_id' => '24'],
            ['id' => '951', 'title' => 'پاتاوه', 'parent_id' => '24'],
            ['id' => '952', 'title' => 'چرام', 'parent_id' => '24'],
            ['id' => '953', 'title' => 'چيتاب', 'parent_id' => '24'],
            ['id' => '954', 'title' => 'دوگنبدان', 'parent_id' => '24'],
            ['id' => '955', 'title' => 'دهدشت', 'parent_id' => '24'],
            ['id' => '956', 'title' => 'ديشموك', 'parent_id' => '24'],
            ['id' => '957', 'title' => 'سرفارياب', 'parent_id' => '24'],
            ['id' => '958', 'title' => 'سوق', 'parent_id' => '24'],
            ['id' => '959', 'title' => 'سي سخت', 'parent_id' => '24'],
            ['id' => '960', 'title' => 'قلعه رئيسي', 'parent_id' => '24'],
            ['id' => '961', 'title' => 'گراب سفلي', 'parent_id' => '24'],
            ['id' => '962', 'title' => 'لنده', 'parent_id' => '24'],
            ['id' => '963', 'title' => 'ليكك', 'parent_id' => '24'],
            ['id' => '964', 'title' => 'مادوان', 'parent_id' => '24'],
            ['id' => '965', 'title' => 'مارگون', 'parent_id' => '24'],
            ['id' => '966', 'title' => 'ياسوج', 'parent_id' => '24'],
            ['id' => '967', 'title' => 'انبارآلوم', 'parent_id' => '25'],
            ['id' => '968', 'title' => 'اينچه برون', 'parent_id' => '25'],
            ['id' => '969', 'title' => 'آزادشهر', 'parent_id' => '25'],
            ['id' => '970', 'title' => 'آق قلا', 'parent_id' => '25'],
            ['id' => '971', 'title' => 'بندرتركمن', 'parent_id' => '25'],
            ['id' => '972', 'title' => 'بندرگز', 'parent_id' => '25'],
            ['id' => '973', 'title' => 'تاتارعليا', 'parent_id' => '25'],
            ['id' => '974', 'title' => 'جلين', 'parent_id' => '25'],
            ['id' => '975', 'title' => 'خان ببين', 'parent_id' => '25'],
            ['id' => '976', 'title' => 'دلند', 'parent_id' => '25'],
            ['id' => '977', 'title' => 'راميان', 'parent_id' => '25'],
            ['id' => '978', 'title' => 'سرخنكلاته', 'parent_id' => '25'],
            ['id' => '979', 'title' => 'سنگدوين', 'parent_id' => '25'],
            ['id' => '980', 'title' => 'سيمين شهر', 'parent_id' => '25'],
            ['id' => '981', 'title' => 'علي اباد', 'parent_id' => '25'],
            ['id' => '982', 'title' => 'فاضل آباد', 'parent_id' => '25'],
            ['id' => '983', 'title' => 'فراغي', 'parent_id' => '25'],
            ['id' => '984', 'title' => 'كردكوئ', 'parent_id' => '25'],
            ['id' => '985', 'title' => 'كلاله', 'parent_id' => '25'],
            ['id' => '986', 'title' => 'گاليكش', 'parent_id' => '25'],
            ['id' => '987', 'title' => 'گرگان', 'parent_id' => '25'],
            ['id' => '988', 'title' => 'ارسباران', 'parent_id' => '2'],
            ['id' => '989', 'title' => 'چاراویماق', 'parent_id' => '2'],
            ['id' => '990', 'title' => 'گميش تپه', 'parent_id' => '25'],
            ['id' => '991', 'title' => 'گنبدكاووس', 'parent_id' => '25'],
            ['id' => '992', 'title' => 'مراوه', 'parent_id' => '25'],
            ['id' => '993', 'title' => 'مزرعه', 'parent_id' => '25'],
            ['id' => '994', 'title' => 'مينودشت', 'parent_id' => '25'],
            ['id' => '995', 'title' => 'نگين شهر', 'parent_id' => '25'],
            ['id' => '996', 'title' => 'نوده خاندوز', 'parent_id' => '25'],
            ['id' => '997', 'title' => 'نوكنده', 'parent_id' => '25'],
            ['id' => '998', 'title' => 'ازنا', 'parent_id' => '27'],
            ['id' => '999', 'title' => 'اشترينان', 'parent_id' => '27'],
            ['id' => '1000', 'title' => 'الشتر', 'parent_id' => '27'],
            ['id' => '1001', 'title' => 'اليگودرز', 'parent_id' => '27'],
            ['id' => '1002', 'title' => 'بروجرد', 'parent_id' => '27'],
            ['id' => '1003', 'title' => 'بيران شهر', 'parent_id' => '27'],
            ['id' => '1004', 'title' => 'پلدختر', 'parent_id' => '27'],
            ['id' => '1005', 'title' => 'چالانچولان', 'parent_id' => '27'],
            ['id' => '1006', 'title' => 'چقابل', 'parent_id' => '27'],
            ['id' => '1007', 'title' => 'خرم آباد', 'parent_id' => '27'],
            ['id' => '1008', 'title' => 'درب گنبد', 'parent_id' => '27'],
            ['id' => '1009', 'title' => 'دورود', 'parent_id' => '27'],
            ['id' => '1010', 'title' => 'زاغه', 'parent_id' => '27'],
            ['id' => '1011', 'title' => 'سپيددشت', 'parent_id' => '27'],
            ['id' => '1012', 'title' => 'سراب دوره', 'parent_id' => '27'],
            ['id' => '1013', 'title' => 'شول آباد', 'parent_id' => '27'],
            ['id' => '1014', 'title' => 'فيروزآباد', 'parent_id' => '27'],
            ['id' => '1015', 'title' => 'کوهدشت', 'parent_id' => '27'],
            ['id' => '1016', 'title' => 'کوهناني', 'parent_id' => '27'],
            ['id' => '1017', 'title' => 'گراب', 'parent_id' => '27'],
            ['id' => '1018', 'title' => 'معمولان', 'parent_id' => '27'],
            ['id' => '1019', 'title' => 'مومن آباد', 'parent_id' => '27'],
            ['id' => '1020', 'title' => 'نورآباد', 'parent_id' => '27'],
            ['id' => '1021', 'title' => 'ويسيان', 'parent_id' => '27'],
            ['id' => '1022', 'title' => 'هفت چشمه', 'parent_id' => '27'],
            ['id' => '1023', 'title' => 'احمدسرگوراب', 'parent_id' => '26'],
            ['id' => '1024', 'title' => 'اسالم', 'parent_id' => '26'],
            ['id' => '1025', 'title' => 'اطاقور', 'parent_id' => '26'],
            ['id' => '1026', 'title' => 'املش', 'parent_id' => '26'],
            ['id' => '1027', 'title' => 'آستارا', 'parent_id' => '26'],
            ['id' => '1028', 'title' => 'آستانه اشرفيه', 'parent_id' => '26'],
            ['id' => '1029', 'title' => 'بازار جمعه', 'parent_id' => '26'],
            ['id' => '1030', 'title' => 'بره سر', 'parent_id' => '26'],
            ['id' => '1031', 'title' => 'بندرانزلي', 'parent_id' => '26'],
            ['id' => '1032', 'title' => 'پره سر', 'parent_id' => '26'],
            ['id' => '1033', 'title' => 'تالش', 'parent_id' => '26'],
            ['id' => '1034', 'title' => 'توتكابن', 'parent_id' => '26'],
            ['id' => '1035', 'title' => 'جيرنده', 'parent_id' => '26'],
            ['id' => '1036', 'title' => 'چابكسر', 'parent_id' => '26'],
            ['id' => '1037', 'title' => 'چاف و چمخاله', 'parent_id' => '26'],
            ['id' => '1038', 'title' => 'چوبر', 'parent_id' => '26'],
            ['id' => '1039', 'title' => 'حويق', 'parent_id' => '26'],
            ['id' => '1040', 'title' => 'خشكبيجار', 'parent_id' => '26'],
            ['id' => '1041', 'title' => 'خمام', 'parent_id' => '26'],
            ['id' => '1042', 'title' => 'ديلمان', 'parent_id' => '26'],
            ['id' => '1043', 'title' => 'رانكوه', 'parent_id' => '26'],
            ['id' => '1044', 'title' => 'رحيم آباد', 'parent_id' => '26'],
            ['id' => '1045', 'title' => 'رستم آباد', 'parent_id' => '26'],
            ['id' => '1046', 'title' => 'رشت', 'parent_id' => '26'],
            ['id' => '1047', 'title' => 'آمل', 'parent_id' => '28'],
            ['id' => '1048', 'title' => 'بابل', 'parent_id' => '28'],
            ['id' => '1049', 'title' => 'بابلسر', 'parent_id' => '28'],
            ['id' => '1050', 'title' => 'بهشهر', 'parent_id' => '28'],
            ['id' => '1051', 'title' => 'جویبار', 'parent_id' => '28'],
            ['id' => '1052', 'title' => 'چالوس', 'parent_id' => '28'],
            ['id' => '1053', 'title' => 'کلاردشت', 'parent_id' => '28'],
            ['id' => '1054', 'title' => 'رامسر', 'parent_id' => '28'],
            ['id' => '1055', 'title' => 'ساری', 'parent_id' => '28'],
            ['id' => '1056', 'title' => 'سواد کوه', 'parent_id' => '28'],
            ['id' => '1057', 'title' => 'سوادکوه شمالی', 'parent_id' => '28'],
            ['id' => '1058', 'title' => 'سیمرغ', 'parent_id' => '28'],
            ['id' => '1059', 'title' => 'تنکابن', 'parent_id' => '28'],
            ['id' => '1060', 'title' => 'عباس آباد', 'parent_id' => '28'],
            ['id' => '1061', 'title' => 'فریدون کنار', 'parent_id' => '28'],
            ['id' => '1062', 'title' => 'قائم‌ شهر', 'parent_id' => '28'],
            ['id' => '1063', 'title' => 'سوادکوه شمالی', 'parent_id' => '28'],
            ['id' => '1064', 'title' => 'گلوگاه', 'parent_id' => '28'],
            ['id' => '1065', 'title' => 'محمود آباد', 'parent_id' => '28'],
            ['id' => '1066', 'title' => 'میان‌ دورود', 'parent_id' => '28'],
            ['id' => '1067', 'title' => 'نکا', 'parent_id' => '28'],
            ['id' => '1068', 'title' => 'نوشهر', 'parent_id' => '28'],
            ['id' => '1069', 'title' => 'نور', 'parent_id' => '28'],
            ['id' => '1070', 'title' => 'اراک', 'parent_id' => '29'],
            ['id' => '1071', 'title' => 'ساوه', 'parent_id' => '29'],
            ['id' => '1072', 'title' => 'خمین', 'parent_id' => '29'],
            ['id' => '1073', 'title' => 'محلات', 'parent_id' => '29'],
            ['id' => '1074', 'title' => 'دلیجان', 'parent_id' => '29'],
            ['id' => '1075', 'title' => 'کرهرود', 'parent_id' => '29'],
            ['id' => '1076', 'title' => 'شازند', 'parent_id' => '29'],
            ['id' => '1077', 'title' => 'مأمونیه', 'parent_id' => '29'],
            ['id' => '1078', 'title' => 'تفرش', 'parent_id' => '29'],
            ['id' => '1079', 'title' => 'مهاجران', 'parent_id' => '29'],
            ['id' => '1080', 'title' => 'سنجان', 'parent_id' => '29'],
            ['id' => '1081', 'title' => 'میلاجرد', 'parent_id' => '29'],
            ['id' => '1082', 'title' => 'کمیجان', 'parent_id' => '29'],
            ['id' => '1083', 'title' => 'آشتیان', 'parent_id' => '29'],
            ['id' => '1084', 'title' => 'خنداب', 'parent_id' => '29'],
            ['id' => '1085', 'title' => 'آستانه', 'parent_id' => '29'],
            ['id' => '1086', 'title' => 'پرندک', 'parent_id' => '29'],
            ['id' => '1087', 'title' => 'زاویه', 'parent_id' => '29'],
            ['id' => '1088', 'title' => 'نیم‌ ور', 'parent_id' => '29'],
            ['id' => '1089', 'title' => 'داودآباد', 'parent_id' => '29'],
            ['id' => '1090', 'title' => 'خشکرود', 'parent_id' => '29'],
            ['id' => '1091', 'title' => 'غرق‌ آباد', 'parent_id' => '29'],
            ['id' => '1092', 'title' => 'جاورسیان', 'parent_id' => '29'],
            ['id' => '1093', 'title' => 'فرمهین', 'parent_id' => '29'],
            ['id' => '1094', 'title' => 'خنجین', 'parent_id' => '29'],
            ['id' => '1095', 'title' => 'کارچان', 'parent_id' => '29'],
            ['id' => '1096', 'title' => 'نراق', 'parent_id' => '29'],
            ['id' => '1097', 'title' => 'توره', 'parent_id' => '29'],
            ['id' => '1098', 'title' => 'نوبران', 'parent_id' => '29'],
            ['id' => '1099', 'title' => 'هندودر', 'parent_id' => '29'],
            ['id' => '1100', 'title' => 'قورچی‌ باشی', 'parent_id' => '29'],
            ['id' => '1101', 'title' => 'ساروق', 'parent_id' => '29'],
            ['id' => '1102', 'title' => 'رازقان', 'parent_id' => '29'],
            ['id' => '1103', 'title' => 'شهباز', 'parent_id' => '29'],
            ['id' => '1104', 'title' => 'بندرعباس', 'parent_id' => '30'],
            ['id' => '1105', 'title' => 'میناب', 'parent_id' => '30'],
            ['id' => '1106', 'title' => 'دهبارز', 'parent_id' => '30'],
            ['id' => '1107', 'title' => 'بندر لنگه', 'parent_id' => '30'],
            ['id' => '1108', 'title' => 'قشم', 'parent_id' => '30'],
            ['id' => '1109', 'title' => 'کیش', 'parent_id' => '30'],
            ['id' => '1110', 'title' => 'حاجی آباد', 'parent_id' => '30'],
            ['id' => '1111', 'title' => 'کَنگ', 'parent_id' => '30'],
            ['id' => '1112', 'title' => 'بندر خمیر', 'parent_id' => '30'],
            ['id' => '1113', 'title' => 'جاسک', 'parent_id' => '30'],
            ['id' => '1114', 'title' => 'پارسیان', 'parent_id' => '30'],
            ['id' => '1115', 'title' => 'بستک', 'parent_id' => '30'],
            ['id' => '1116', 'title' => 'درگهان', 'parent_id' => '30'],
            ['id' => '1117', 'title' => 'جناح', 'parent_id' => '30'],
            ['id' => '1118', 'title' => 'بیکا', 'parent_id' => '30'],
            ['id' => '1119', 'title' => 'رویدر', 'parent_id' => '30'],
            ['id' => '1120', 'title' => 'هرمز', 'parent_id' => '30'],
            ['id' => '1121', 'title' => 'فین', 'parent_id' => '30'],
            ['id' => '1122', 'title' => 'قلعه قاضی', 'parent_id' => '30'],
            ['id' => '1123', 'title' => 'سوزا', 'parent_id' => '30'],
            ['id' => '1124', 'title' => 'هشت‌ بندی', 'parent_id' => '30'],
            ['id' => '1125', 'title' => 'سیریک', 'parent_id' => '30'],
            ['id' => '1126', 'title' => 'بندر چارک', 'parent_id' => '30'],
            ['id' => '1127', 'title' => 'ابوموسی', 'parent_id' => '30'],
            ['id' => '1128', 'title' => 'زیارت‌ علی', 'parent_id' => '30'],
            ['id' => '1129', 'title' => 'کوشکنار', 'parent_id' => '30'],
            ['id' => '1130', 'title' => 'تخت', 'parent_id' => '30'],
            ['id' => '1131', 'title' => 'سندرک', 'parent_id' => '30'],
            ['id' => '1132', 'title' => 'فارغان', 'parent_id' => '30'],
            ['id' => '1133', 'title' => 'سردشت', 'parent_id' => '30'],
            ['id' => '1134', 'title' => 'گوهران', 'parent_id' => '30'],
            ['id' => '1135', 'title' => 'همدان', 'parent_id' => '31'],
            ['id' => '1136', 'title' => 'ملایر', 'parent_id' => '31'],
            ['id' => '1137', 'title' => 'نهاوند', 'parent_id' => '31'],
            ['id' => '1138', 'title' => 'اسد آباد', 'parent_id' => '31'],
            ['id' => '1139', 'title' => 'تویسرکان', 'parent_id' => '31'],
            ['id' => '1140', 'title' => 'بهار', 'parent_id' => '31'],
            ['id' => '1141', 'title' => 'کبودرآهنگ', 'parent_id' => '31'],
            ['id' => '1142', 'title' => 'لالجین', 'parent_id' => '31'],
            ['id' => '1143', 'title' => 'فامنین', 'parent_id' => '31'],
            ['id' => '1144', 'title' => 'رزن', 'parent_id' => '31'],
            ['id' => '1145', 'title' => 'قروه درجزین', 'parent_id' => '31'],
            ['id' => '1146', 'title' => 'مریانج', 'parent_id' => '31'],
            ['id' => '1147', 'title' => 'ازندریان', 'parent_id' => '31'],
            ['id' => '1148', 'title' => 'جورقان', 'parent_id' => '31'],
            ['id' => '1149', 'title' => 'گیان', 'parent_id' => '31'],
            ['id' => '1150', 'title' => 'صالح‌ آباد', 'parent_id' => '31'],
            ['id' => '1151', 'title' => 'فیروزان', 'parent_id' => '31'],
            ['id' => '1152', 'title' => 'سامن', 'parent_id' => '31'],
            ['id' => '1153', 'title' => 'سرکان', 'parent_id' => '31'],
            ['id' => '1154', 'title' => 'دمق', 'parent_id' => '31'],
            ['id' => '1155', 'title' => 'اسلام‌ شهر آق‌ گل', 'parent_id' => '31'],
            ['id' => '1156', 'title' => 'آجین', 'parent_id' => '31'],
            ['id' => '1157', 'title' => 'قهاوند', 'parent_id' => '31'],
            ['id' => '1158', 'title' => 'شیرین‌ سو', 'parent_id' => '31'],
            ['id' => '1159', 'title' => 'برزول', 'parent_id' => '31'],
            ['id' => '1160', 'title' => 'گل‌ تپه', 'parent_id' => '31'],
            ['id' => '1161', 'title' => 'جوکار', 'parent_id' => '31'],
            ['id' => '1162', 'title' => 'فرسفج', 'parent_id' => '31'],
            ['id' => '1163', 'title' => 'زنگنه', 'parent_id' => '31'],
            ['id' => '1164', 'title' => 'یزد', 'parent_id' => '32'],
            ['id' => '1165', 'title' => 'میبد', 'parent_id' => '32'],
            ['id' => '1166', 'title' => 'اردکان', 'parent_id' => '32'],
            ['id' => '1167', 'title' => 'حمیدیا', 'parent_id' => '32'],
            ['id' => '1168', 'title' => 'بافق', 'parent_id' => '32'],
            ['id' => '1169', 'title' => 'مهریز', 'parent_id' => '32'],
            ['id' => '1170', 'title' => 'ابرکوه', 'parent_id' => '32'],
            ['id' => '1171', 'title' => 'شاهدیه', 'parent_id' => '32'],
            ['id' => '1172', 'title' => 'تفت', 'parent_id' => '32'],
            ['id' => '1173', 'title' => 'اشکذر', 'parent_id' => '32'],
            ['id' => '1174', 'title' => 'زارچ', 'parent_id' => '32'],
            ['id' => '1175', 'title' => 'هرات', 'parent_id' => '32'],
            ['id' => '1176', 'title' => 'مروست', 'parent_id' => '32'],
            ['id' => '1177', 'title' => 'بهاباد', 'parent_id' => '32'],
            ['id' => '1178', 'title' => 'مهردشت', 'parent_id' => '32'],
            ['id' => '1179', 'title' => 'بفروئیه', 'parent_id' => '32'],
            ['id' => '1180', 'title' => 'احمدآباد', 'parent_id' => '32'],
            ['id' => '1181', 'title' => 'خضرآباد', 'parent_id' => '32'],
            ['id' => '1182', 'title' => 'ندوشن', 'parent_id' => '32'],
            ['id' => '1183', 'title' => 'عقدا', 'parent_id' => '32'],
            ['id' => '1184', 'title' => 'نیر', 'parent_id' => '32'],
            ['id' => '1185', 'title' => 'سنندج', 'parent_id' => '21'],
            ['id' => '1186', 'title' => 'قروه', 'parent_id' => '21'],
            ['id' => '1187', 'title' => 'کامیاران', 'parent_id' => '21'],
            ['id' => '1188', 'title' => 'مریوان', 'parent_id' => '21'],
            ['id' => '1189', 'title' => 'رضوانشهر', 'parent_id' => '26'],
            ['id' => '1190', 'title' => 'رودبار', 'parent_id' => '26'],
            ['id' => '1191', 'title' => 'منجیل', 'parent_id' => '26'],
            ['id' => '1192', 'title' => 'لوشان', 'parent_id' => '26'],
            ['id' => '1193', 'title' => 'رودسر', 'parent_id' => '26'],
            ['id' => '1194', 'title' => 'کلاچای', 'parent_id' => '26'],
            ['id' => '1195', 'title' => 'شفت', 'parent_id' => '26'],
            ['id' => '1196', 'title' => 'سیاهکل', 'parent_id' => '26'],
            ['id' => '1197', 'title' => 'صومعه سرا', 'parent_id' => '26'],
            ['id' => '1198', 'title' => 'فومن ', 'parent_id' => '26'],
            ['id' => '1199', 'title' => 'لاهیجان', 'parent_id' => '26'],
            ['id' => '1200', 'title' => 'لنگرود', 'parent_id' => '26'],
            ['id' => '1201', 'title' => 'زیباکنار', 'parent_id' => '26'],
            ['id' => '1202', 'title' => 'چالدران', 'parent_id' => '3'],
            ['id' => '1203', 'title' => 'کوثر', 'parent_id' => '4'],
            ['id' => '1204', 'title' => 'فریدن', 'parent_id' => '5'],
            ['id' => '1205', 'title' => 'لنجان', 'parent_id' => '5'],
            ['id' => '1206', 'title' => 'چرداول', 'parent_id' => '7'],
            ['id' => '1207', 'title' => 'ملک شاهی', 'parent_id' => '7'],
            ['id' => '1208', 'title' => 'دشتستان', 'parent_id' => '8'],
            ['id' => '1209', 'title' => 'کنگان', 'parent_id' => '8'],
            ['id' => '1210', 'title' => 'تنگستان', 'parent_id' => '8'],
            ['id' => '1211', 'title' => 'دیلم', 'parent_id' => '8'],
            ['id' => '1212', 'title' => 'کوهرنگ', 'parent_id' => '10'],
            ['id' => '1213', 'title' => 'کیار', 'parent_id' => '10'],
            ['id' => '1214', 'title' => 'درمیان', 'parent_id' => '11'],
            ['id' => '1215', 'title' => 'زیرکوه', 'parent_id' => '11'],
            ['id' => '1216', 'title' => 'زاوه', 'parent_id' => '12'],
            ['id' => '1217', 'title' => 'مه ولات', 'parent_id' => '12'],
            ['id' => '1218', 'title' => 'مانه و سملقان', 'parent_id' => '13'],
            ['id' => '1219', 'title' => 'دشت ازادگان', 'parent_id' => '14'],
            ['id' => '1220', 'title' => 'خدابنده', 'parent_id' => '15'],
            ['id' => '1221', 'title' => 'طارم', 'parent_id' => '15'],
            ['id' => '1222', 'title' => 'ایجرود', 'parent_id' => '15'],
            ['id' => '1223', 'title' => 'هیرمند', 'parent_id' => '17'],
            ['id' => '1224', 'title' => 'ممسنی', 'parent_id' => '18'],
            ['id' => '1225', 'title' => 'پاسارگاد', 'parent_id' => '18'],
            ['id' => '1226', 'title' => 'خرم بید', 'parent_id' => '18'],
            ['id' => '1227', 'title' => 'زرین دشت', 'parent_id' => '18'],
            ['id' => '1228', 'title' => 'رستم', 'parent_id' => '18'],
            ['id' => '1229', 'title' => 'البرز', 'parent_id' => '19'],
            ['id' => '1230', 'title' => 'ماسال', 'parent_id' => '26'],
            ['id' => '1231', 'title' => 'دلفان', 'parent_id' => '27'],
            ['id' => '1232', 'title' => 'سلسله', 'parent_id' => '27'],
            ['id' => '1233', 'title' => 'زرندیه', 'parent_id' => '29'],
            ['id' => '1234', 'title' => 'بشاگرد', 'parent_id' => '30'],
            ['id' => '1235', 'title' => 'رودان', 'parent_id' => '30'],
            ['id' => '1236', 'title' => 'خاتم', 'parent_id' => '30'],
            ['id' => '1237', 'title' => 'صدوق', 'parent_id' => '32'],
            ['id' => '1238', 'title' => 'گچ سران', 'parent_id' => '24'],
            ['id' => '1239', 'title' => 'بهمنی', 'parent_id' => '24'],
            ['id' => '1240', 'title' => 'دنا', 'parent_id' => '24'],

        ]);

    }
}
